/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package som.mod.som.form;

import erp.lib.SLibUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiParams;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanForm;
import som.gui.SGuiClientUtils;
import som.mod.SModConsts;
import som.mod.SModSysConsts;
import som.mod.som.db.SDbItem;
import som.mod.som.db.SDbProducer;
import som.mod.som.db.SDbTicketAlternative;
import som.mod.som.db.SSomConsts;
import som.mod.som.db.SSomUtils;

/**
 * Forma de captura de boletos de báscula alternativos.
 * IMPORTANTE: Considérese que la forma no es propiamente para crear nuevos registro, sino solo para modificarlos.
 * @author Isabel Servín, Sergio Flores
 */
public class SFormTicketAlternative extends SBeanForm implements ActionListener, ItemListener, FocusListener {

    private SDbTicketAlternative moRegistry;
    private SDbItem moItem;
    private SDbProducer moProducer;
    private int mnSeasonId;
    private int mnRegionId;
    private boolean mbIsPacking;
    private boolean mbIsLaboratory;
    private boolean mbIsRevImport1;
    private boolean mbIsRevImport2;
    
    String arrWeiChgIds[];
    
    /**
     * Creates new form SFormTicket
     * @param client GUI client.
     * @param title Form title.
     * @param formSubType Form subtype: 1) normal ticket: SLibConsts.UNDEFINED; 2) ticket to be tared: SModConsts.SX_TIC_TARE_PEND.
     */
    public SFormTicketAlternative(SGuiClient client, int formSubType, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.S_ALT_TIC, formSubType, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jlScale = new javax.swing.JLabel();
        moKeyScale = new sa.lib.gui.bean.SBeanFieldKey();
        jtfScale = new javax.swing.JTextField();
        moBoolTared = new sa.lib.gui.bean.SBeanFieldBoolean();
        jPanel4 = new javax.swing.JPanel();
        jlTicket = new javax.swing.JLabel();
        moTextTicket = new sa.lib.gui.bean.SBeanFieldText();
        jlDummy = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jlProducer = new javax.swing.JLabel();
        moKeyProducer = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel12 = new javax.swing.JPanel();
        jlItem = new javax.swing.JLabel();
        moKeyItem = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel21 = new javax.swing.JPanel();
        jlInputSource = new javax.swing.JLabel();
        moKeyInputSource = new sa.lib.gui.bean.SBeanFieldKey();
        jbSetDefaultInputSource = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jlPlates = new javax.swing.JLabel();
        moTextPlates = new sa.lib.gui.bean.SBeanFieldText();
        jlPlatesCage = new javax.swing.JLabel();
        moTextPlatesCage = new sa.lib.gui.bean.SBeanFieldText();
        jlPlatesCage1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlDriver = new javax.swing.JLabel();
        moTextDriver = new sa.lib.gui.bean.SBeanFieldText();
        jPanel7 = new javax.swing.JPanel();
        jlWeightSource = new javax.swing.JLabel();
        moDecWeightSource = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightSourceUnit = new javax.swing.JLabel();
        moBoolWeightSourceAvailable = new sa.lib.gui.bean.SBeanFieldBoolean();
        jPanel9 = new javax.swing.JPanel();
        jlWeightDestinyArrival = new javax.swing.JLabel();
        moDecWeightDestinyArrival = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightDestinyArrivalUnit = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jlWeightDestinyDeparture = new javax.swing.JLabel();
        moDecWeightDestinyDeparture = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightDestinyDepartureUnit = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jlDatetimeArrival = new javax.swing.JLabel();
        moDatetimeArrival = new sa.lib.gui.bean.SBeanFieldDatetime();
        jLabel1 = new javax.swing.JLabel();
        jlScaleOperatorArrival = new javax.swing.JLabel();
        moTextScaleOperatorArrival = new sa.lib.gui.bean.SBeanFieldText();
        jPanel11 = new javax.swing.JPanel();
        jlDatetimeDeparture = new javax.swing.JLabel();
        moDatetimeDeparture = new sa.lib.gui.bean.SBeanFieldDatetime();
        jLabel2 = new javax.swing.JLabel();
        jlScaleOperatorDeparture = new javax.swing.JLabel();
        moTextScaleOperatorDeparture = new sa.lib.gui.bean.SBeanFieldText();
        jPanel5 = new javax.swing.JPanel();
        jlNote = new javax.swing.JLabel();
        moTextNote = new sa.lib.gui.bean.SBeanFieldText();
        jPanel14 = new javax.swing.JPanel();
        jlNote2 = new javax.swing.JLabel();
        moTextNote2 = new sa.lib.gui.bean.SBeanFieldText();
        jPanel17 = new javax.swing.JPanel();
        jlPacking = new javax.swing.JLabel();
        jlPackingFull = new javax.swing.JLabel();
        jlPacking1 = new javax.swing.JLabel();
        jlPackingEmpty = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jlPackingQuantityArrival = new javax.swing.JLabel();
        moDecPackingFullQuantityArrival = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingFullQuantityArrivalUnits = new javax.swing.JLabel();
        jlPackingQuantityArrival1 = new javax.swing.JLabel();
        moDecPackingEmptyQuantityArrival = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingEmptyQuantityArrivalUnits = new javax.swing.JLabel();
        jlPackingQuantityArrival2 = new javax.swing.JLabel();
        jlPackingWeight = new javax.swing.JLabel();
        moDecPackingWeight = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingWeightUnit = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jlPackingQuantityDeparture = new javax.swing.JLabel();
        moDecPackingFullQuantityDeparture = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingFullQuantityDepartureUnits = new javax.swing.JLabel();
        jlPackingQuantityDeparture1 = new javax.swing.JLabel();
        moDecPackingEmptyQuantityDeparture = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingEmptyQuantityDepartureUnits = new javax.swing.JLabel();
        jlPackingQuantityDeparture2 = new javax.swing.JLabel();
        jlWeightAverage = new javax.swing.JLabel();
        moDecWeightAverage = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightAverageUnits = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jlWeightDestinyNetComputed = new javax.swing.JLabel();
        moDecWeightDestinyNetComputed = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightDestinyNetComputedUnit = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jlWeightDestinyNet = new javax.swing.JLabel();
        moDecWeightDestinyNet = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightDestinyNetUnit = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(20, 1, 0, 5));

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlScale.setForeground(new java.awt.Color(51, 51, 255));
        jlScale.setText("Báscula:*");
        jlScale.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel13.add(jlScale);

        moKeyScale.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel13.add(moKeyScale);

        jtfScale.setEditable(false);
        jtfScale.setText("TEXT");
        jtfScale.setFocusable(false);
        jtfScale.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel13.add(jtfScale);

        moBoolTared.setText("Boleto tarado");
        moBoolTared.setEditable(false);
        jPanel13.add(moBoolTared);

        jPanel2.add(jPanel13);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTicket.setText("Boleto:*");
        jlTicket.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel4.add(jlTicket);

        moTextTicket.setText("TEXT");
        jPanel4.add(moTextTicket);

        jlDummy.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel4.add(jlDummy);

        jPanel2.add(jPanel4);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlProducer.setText("Proveedor:*");
        jlProducer.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel10.add(jlProducer);

        moKeyProducer.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel10.add(moKeyProducer);

        jPanel2.add(jPanel10);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlItem.setText("Ítem:*");
        jlItem.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel12.add(jlItem);

        moKeyItem.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel12.add(moKeyItem);

        jPanel2.add(jPanel12);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlInputSource.setText("Origen del insumo:*");
        jlInputSource.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel21.add(jlInputSource);

        moKeyInputSource.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel21.add(moKeyInputSource);

        jbSetDefaultInputSource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_wizard.gif"))); // NOI18N
        jbSetDefaultInputSource.setToolTipText("Seleccionar origen insumo del proveedor");
        jbSetDefaultInputSource.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel21.add(jbSetDefaultInputSource);

        jPanel2.add(jPanel21);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPlates.setText("Placas del vehículo:*");
        jlPlates.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel6.add(jlPlates);

        moTextPlates.setText("TEXT");
        jPanel6.add(moTextPlates);

        jlPlatesCage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPlatesCage.setText("Placas caja:");
        jlPlatesCage.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel6.add(jlPlatesCage);

        moTextPlatesCage.setText("TEXT");
        jPanel6.add(moTextPlatesCage);

        jlPlatesCage1.setForeground(java.awt.SystemColor.textInactiveText);
        jlPlatesCage1.setText("(Placas de la caja o remolque del vehículo.)");
        jlPlatesCage1.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel6.add(jlPlatesCage1);

        jPanel2.add(jPanel6);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDriver.setText("Chofer del vehículo:*");
        jlDriver.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel3.add(jlDriver);

        moTextDriver.setText("TEXT");
        moTextDriver.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel3.add(moTextDriver);

        jPanel2.add(jPanel3);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightSource.setText("Peso origen:*");
        jlWeightSource.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel7.add(jlWeightSource);
        jPanel7.add(moDecWeightSource);

        jlWeightSourceUnit.setText("UNIT");
        jlWeightSourceUnit.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlWeightSourceUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel7.add(jlWeightSourceUnit);

        moBoolWeightSourceAvailable.setText("Peso origen disponible");
        moBoolWeightSourceAvailable.setPreferredSize(new java.awt.Dimension(165, 23));
        jPanel7.add(moBoolWeightSourceAvailable);

        jPanel2.add(jPanel7);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightDestinyArrival.setText("Peso en entrada:*");
        jlWeightDestinyArrival.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel9.add(jlWeightDestinyArrival);
        jPanel9.add(moDecWeightDestinyArrival);

        jlWeightDestinyArrivalUnit.setText("UNIT");
        jlWeightDestinyArrivalUnit.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlWeightDestinyArrivalUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel9.add(jlWeightDestinyArrivalUnit);

        jPanel2.add(jPanel9);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightDestinyDeparture.setText("Peso en salida:*");
        jlWeightDestinyDeparture.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel15.add(jlWeightDestinyDeparture);
        jPanel15.add(moDecWeightDestinyDeparture);

        jlWeightDestinyDepartureUnit.setText("UNIT");
        jlWeightDestinyDepartureUnit.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlWeightDestinyDepartureUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel15.add(jlWeightDestinyDepartureUnit);

        jPanel2.add(jPanel15);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDatetimeArrival.setText("Fecha-hora de entrada:*");
        jlDatetimeArrival.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel8.add(jlDatetimeArrival);
        jPanel8.add(moDatetimeArrival);

        jLabel1.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel8.add(jLabel1);

        jlScaleOperatorArrival.setText("Operador báscula en entrada:");
        jlScaleOperatorArrival.setPreferredSize(new java.awt.Dimension(175, 23));
        jPanel8.add(jlScaleOperatorArrival);

        moTextScaleOperatorArrival.setText("TEXT");
        moTextScaleOperatorArrival.setPreferredSize(new java.awt.Dimension(227, 23));
        jPanel8.add(moTextScaleOperatorArrival);

        jPanel2.add(jPanel8);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDatetimeDeparture.setText("Fecha-hora de salida:*");
        jlDatetimeDeparture.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel11.add(jlDatetimeDeparture);
        jPanel11.add(moDatetimeDeparture);

        jLabel2.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel11.add(jLabel2);

        jlScaleOperatorDeparture.setText("Operador báscula en salida:");
        jlScaleOperatorDeparture.setPreferredSize(new java.awt.Dimension(175, 23));
        jPanel11.add(jlScaleOperatorDeparture);

        moTextScaleOperatorDeparture.setText("TEXT");
        moTextScaleOperatorDeparture.setPreferredSize(new java.awt.Dimension(227, 23));
        jPanel11.add(moTextScaleOperatorDeparture);

        jPanel2.add(jPanel11);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlNote.setText("Observaciones entrada:");
        jlNote.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel5.add(jlNote);

        moTextNote.setText("TEXT");
        moTextNote.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel5.add(moTextNote);

        jPanel2.add(jPanel5);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlNote2.setText("Observaciones salida:");
        jlNote2.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel14.add(jlNote2);

        moTextNote2.setText("TEXT");
        moTextNote2.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel14.add(moTextNote2);

        jPanel2.add(jPanel14);

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPacking.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel17.add(jlPacking);

        jlPackingFull.setText("Envases llenos:");
        jlPackingFull.setPreferredSize(new java.awt.Dimension(155, 23));
        jPanel17.add(jlPackingFull);

        jlPacking1.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel17.add(jlPacking1);

        jlPackingEmpty.setText("Envases vacíos:");
        jlPackingEmpty.setPreferredSize(new java.awt.Dimension(155, 23));
        jPanel17.add(jlPackingEmpty);

        jPanel2.add(jPanel17);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPackingQuantityArrival.setText("Núm. envases en entrada:");
        jlPackingQuantityArrival.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel16.add(jlPackingQuantityArrival);
        jPanel16.add(moDecPackingFullQuantityArrival);

        jlPackingFullQuantityArrivalUnits.setText("PAQ");
        jlPackingFullQuantityArrivalUnits.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlPackingFullQuantityArrivalUnits.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel16.add(jlPackingFullQuantityArrivalUnits);

        jlPackingQuantityArrival1.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel16.add(jlPackingQuantityArrival1);
        jPanel16.add(moDecPackingEmptyQuantityArrival);

        jlPackingEmptyQuantityArrivalUnits.setText("PAQ");
        jlPackingEmptyQuantityArrivalUnits.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlPackingEmptyQuantityArrivalUnits.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel16.add(jlPackingEmptyQuantityArrivalUnits);

        jlPackingQuantityArrival2.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel16.add(jlPackingQuantityArrival2);

        jlPackingWeight.setText("Peso por envase:");
        jlPackingWeight.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel16.add(jlPackingWeight);

        moDecPackingWeight.setEditable(false);
        jPanel16.add(moDecPackingWeight);

        jlPackingWeightUnit.setText("UNIT");
        jlPackingWeightUnit.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlPackingWeightUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel16.add(jlPackingWeightUnit);

        jPanel2.add(jPanel16);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPackingQuantityDeparture.setText("Núm. envases en salida:");
        jlPackingQuantityDeparture.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel18.add(jlPackingQuantityDeparture);
        jPanel18.add(moDecPackingFullQuantityDeparture);

        jlPackingFullQuantityDepartureUnits.setText("PAQ");
        jlPackingFullQuantityDepartureUnits.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlPackingFullQuantityDepartureUnits.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel18.add(jlPackingFullQuantityDepartureUnits);

        jlPackingQuantityDeparture1.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel18.add(jlPackingQuantityDeparture1);
        jPanel18.add(moDecPackingEmptyQuantityDeparture);

        jlPackingEmptyQuantityDepartureUnits.setText("PAQ");
        jlPackingEmptyQuantityDepartureUnits.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlPackingEmptyQuantityDepartureUnits.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel18.add(jlPackingEmptyQuantityDepartureUnits);

        jlPackingQuantityDeparture2.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel18.add(jlPackingQuantityDeparture2);

        jlWeightAverage.setText("Peso promedio:");
        jlWeightAverage.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel18.add(jlWeightAverage);

        moDecWeightAverage.setEditable(false);
        jPanel18.add(moDecWeightAverage);

        jlWeightAverageUnits.setText("PAQ / UNIT");
        jlWeightAverageUnits.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlWeightAverageUnits.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel18.add(jlWeightAverageUnits);

        jPanel2.add(jPanel18);

        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        jPanel2.add(jPanel22);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightDestinyNetComputed.setText("Carga destino neta calculada:");
        jlWeightDestinyNetComputed.setMinimumSize(new java.awt.Dimension(110, 23));
        jlWeightDestinyNetComputed.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel19.add(jlWeightDestinyNetComputed);

        moDecWeightDestinyNetComputed.setEditable(false);
        jPanel19.add(moDecWeightDestinyNetComputed);

        jlWeightDestinyNetComputedUnit.setText("UNIT");
        jlWeightDestinyNetComputedUnit.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlWeightDestinyNetComputedUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel19.add(jlWeightDestinyNetComputedUnit);

        jPanel2.add(jPanel19);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightDestinyNet.setText("Carga destino neta boleto:");
        jlWeightDestinyNet.setMinimumSize(new java.awt.Dimension(110, 23));
        jlWeightDestinyNet.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel20.add(jlWeightDestinyNet);

        moDecWeightDestinyNet.setEditable(false);
        jPanel20.add(moDecWeightDestinyNet);

        jlWeightDestinyNetUnit.setText("UNIT");
        jlWeightDestinyNetUnit.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.activeCaptionBorder));
        jlWeightDestinyNetUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel20.add(jlWeightDestinyNetUnit);

        jPanel2.add(jPanel20);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbSetDefaultInputSource;
    private javax.swing.JLabel jlDatetimeArrival;
    private javax.swing.JLabel jlDatetimeDeparture;
    private javax.swing.JLabel jlDriver;
    private javax.swing.JLabel jlDummy;
    private javax.swing.JLabel jlInputSource;
    private javax.swing.JLabel jlItem;
    private javax.swing.JLabel jlNote;
    private javax.swing.JLabel jlNote2;
    private javax.swing.JLabel jlPacking;
    private javax.swing.JLabel jlPacking1;
    private javax.swing.JLabel jlPackingEmpty;
    private javax.swing.JLabel jlPackingEmptyQuantityArrivalUnits;
    private javax.swing.JLabel jlPackingEmptyQuantityDepartureUnits;
    private javax.swing.JLabel jlPackingFull;
    private javax.swing.JLabel jlPackingFullQuantityArrivalUnits;
    private javax.swing.JLabel jlPackingFullQuantityDepartureUnits;
    private javax.swing.JLabel jlPackingQuantityArrival;
    private javax.swing.JLabel jlPackingQuantityArrival1;
    private javax.swing.JLabel jlPackingQuantityArrival2;
    private javax.swing.JLabel jlPackingQuantityDeparture;
    private javax.swing.JLabel jlPackingQuantityDeparture1;
    private javax.swing.JLabel jlPackingQuantityDeparture2;
    private javax.swing.JLabel jlPackingWeight;
    private javax.swing.JLabel jlPackingWeightUnit;
    private javax.swing.JLabel jlPlates;
    private javax.swing.JLabel jlPlatesCage;
    private javax.swing.JLabel jlPlatesCage1;
    private javax.swing.JLabel jlProducer;
    private javax.swing.JLabel jlScale;
    private javax.swing.JLabel jlScaleOperatorArrival;
    private javax.swing.JLabel jlScaleOperatorDeparture;
    private javax.swing.JLabel jlTicket;
    private javax.swing.JLabel jlWeightAverage;
    private javax.swing.JLabel jlWeightAverageUnits;
    private javax.swing.JLabel jlWeightDestinyArrival;
    private javax.swing.JLabel jlWeightDestinyArrivalUnit;
    private javax.swing.JLabel jlWeightDestinyDeparture;
    private javax.swing.JLabel jlWeightDestinyDepartureUnit;
    private javax.swing.JLabel jlWeightDestinyNet;
    private javax.swing.JLabel jlWeightDestinyNetComputed;
    private javax.swing.JLabel jlWeightDestinyNetComputedUnit;
    private javax.swing.JLabel jlWeightDestinyNetUnit;
    private javax.swing.JLabel jlWeightSource;
    private javax.swing.JLabel jlWeightSourceUnit;
    private javax.swing.JTextField jtfScale;
    private sa.lib.gui.bean.SBeanFieldBoolean moBoolTared;
    private sa.lib.gui.bean.SBeanFieldBoolean moBoolWeightSourceAvailable;
    private sa.lib.gui.bean.SBeanFieldDatetime moDatetimeArrival;
    private sa.lib.gui.bean.SBeanFieldDatetime moDatetimeDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingEmptyQuantityArrival;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingEmptyQuantityDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingFullQuantityArrival;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingFullQuantityDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingWeight;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightAverage;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightDestinyArrival;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightDestinyDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightDestinyNet;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightDestinyNetComputed;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightSource;
    private sa.lib.gui.bean.SBeanFieldKey moKeyInputSource;
    private sa.lib.gui.bean.SBeanFieldKey moKeyItem;
    private sa.lib.gui.bean.SBeanFieldKey moKeyProducer;
    private sa.lib.gui.bean.SBeanFieldKey moKeyScale;
    private sa.lib.gui.bean.SBeanFieldText moTextDriver;
    private sa.lib.gui.bean.SBeanFieldText moTextNote;
    private sa.lib.gui.bean.SBeanFieldText moTextNote2;
    private sa.lib.gui.bean.SBeanFieldText moTextPlates;
    private sa.lib.gui.bean.SBeanFieldText moTextPlatesCage;
    private sa.lib.gui.bean.SBeanFieldText moTextScaleOperatorArrival;
    private sa.lib.gui.bean.SBeanFieldText moTextScaleOperatorDeparture;
    private sa.lib.gui.bean.SBeanFieldText moTextTicket;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 1040, 650);
        
        moKeyScale.setKeySettings(miClient, SGuiUtils.getLabelName(jlScale.getText()), true);
        moTextTicket.setTextSettings(SGuiUtils.getLabelName(jlTicket), 10, 1);
        moKeyProducer.setKeySettings(miClient, SGuiUtils.getLabelName(jlProducer.getText()), true);
        moKeyItem.setKeySettings(miClient, SGuiUtils.getLabelName(jlItem.getText()), true);
        moKeyInputSource.setKeySettings(miClient, SGuiUtils.getLabelName(jlInputSource.getText()), true);
        moTextPlates.setTextSettings(SGuiUtils.getLabelName(jlPlates.getText()), 25);
        moTextPlatesCage.setTextSettings(SGuiUtils.getLabelName(jlPlatesCage.getText()), 25, 0);
        moTextDriver.setTextSettings(SGuiUtils.getLabelName(jlDriver.getText()), 150);
        moBoolWeightSourceAvailable.setBooleanSettings(SGuiUtils.getLabelName(moBoolWeightSourceAvailable.getText()), false);
        moDecWeightSource.setDecimalSettings(SGuiUtils.getLabelName(jlWeightSource.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, true);
        moDecWeightDestinyArrival.setDecimalSettings(SGuiUtils.getLabelName(jlWeightDestinyArrival.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, true);
        moDecWeightDestinyDeparture.setDecimalSettings(SGuiUtils.getLabelName(jlWeightDestinyDeparture.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, true);
        moDatetimeArrival.setDateSettings(miClient, SGuiUtils.getLabelName(jlDatetimeArrival.getText()), true);
        moTextScaleOperatorArrival.setTextSettings(SGuiUtils.getLabelName(jlScaleOperatorArrival.getText()), 35, 0);
        moDatetimeDeparture.setDateSettings(miClient, SGuiUtils.getLabelName(jlDatetimeDeparture.getText()), true);
        moTextScaleOperatorDeparture.setTextSettings(SGuiUtils.getLabelName(jlScaleOperatorDeparture.getText()), 35, 0);
        moTextNote.setTextSettings(SGuiUtils.getLabelName(jlNote.getText()), 500, 0);
        moTextNote2.setTextSettings(SGuiUtils.getLabelName(jlNote2.getText()), 500, 0);
        moDecPackingFullQuantityArrival.setDecimalSettings(SGuiUtils.getLabelName(jlPackingQuantityArrival.getText()) + "/ " + SGuiUtils.getLabelName(jlPackingFull.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecPackingEmptyQuantityArrival.setDecimalSettings(SGuiUtils.getLabelName(jlPackingQuantityArrival.getText()) + "/ " + SGuiUtils.getLabelName(jlPackingEmpty.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecPackingFullQuantityDeparture.setDecimalSettings(SGuiUtils.getLabelName(jlPackingQuantityDeparture.getText()) + "/ " + SGuiUtils.getLabelName(jlPackingFull.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecPackingEmptyQuantityDeparture.setDecimalSettings(SGuiUtils.getLabelName(jlPackingQuantityDeparture.getText()) + "/ " + SGuiUtils.getLabelName(jlPackingEmpty.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecWeightAverage.setDecimalSettings(SGuiUtils.getLabelName(jlWeightAverage.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecWeightDestinyNetComputed.setDecimalSettings(SGuiUtils.getLabelName(jlWeightDestinyNetComputed.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecWeightDestinyNet.setDecimalSettings(SGuiUtils.getLabelName(jlWeightDestinyNetComputed.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        
        moFields.addField(moKeyScale);
        moFields.addField(moTextTicket);
        moFields.addField(moKeyProducer);
        moFields.addField(moKeyItem);
        moFields.addField(moKeyInputSource);
        moFields.addField(moTextPlates);
        moFields.addField(moTextPlatesCage);
        moFields.addField(moTextDriver);
        moFields.addField(moBoolWeightSourceAvailable);
        moFields.addField(moDecWeightSource);
        moFields.addField(moDecWeightDestinyArrival);
        moFields.addField(moDecWeightDestinyDeparture);
        moFields.addField(moDatetimeArrival);
        moFields.addField(moTextScaleOperatorArrival);
        moFields.addField(moDatetimeDeparture);
        moFields.addField(moTextScaleOperatorDeparture);
        moFields.addField(moTextNote);
        moFields.addField(moTextNote2);
        moFields.addField(moDecPackingFullQuantityArrival);
        moFields.addField(moDecPackingEmptyQuantityArrival);
        moFields.addField(moDecPackingFullQuantityDeparture);
        moFields.addField(moDecPackingEmptyQuantityDeparture);
        moFields.addField(moDecWeightAverage);
        moFields.addField(moDecWeightDestinyNetComputed);
        moFields.addField(moDecWeightDestinyNet);

        moFields.setFormButton(jbSave);
        
        jlWeightSourceUnit.setText(SSomConsts.KG);
        jlWeightDestinyArrivalUnit.setText(SSomConsts.KG);
        jlWeightDestinyDepartureUnit.setText(SSomConsts.KG);
        jlPackingWeightUnit.setText(SSomConsts.KG);
        jlWeightDestinyNetComputedUnit.setText(SSomConsts.KG);
        jlWeightDestinyNetUnit.setText(SSomConsts.KG);
    }

    private boolean isRequiredInputSource() {
        return moKeyInputSource.getItemCount() > 1;
    }
    
    private void enableFields() {
        moKeyScale.setEnabled(moRegistry.isRegistryNew() && moKeyScale.getItemCount() > 0 && moKeyScale.getItemCount() != 2);
        moTextTicket.setEditable(true);
        moKeyProducer.setEnabled(true);
        moKeyItem.setEnabled(true);
        moKeyInputSource.setEnabled(isRequiredInputSource());
        jbSetDefaultInputSource.setEnabled(isRequiredInputSource());
        
        moTextPlates.setEditable(true);
        moTextPlatesCage.setEditable(true);
        moTextDriver.setEditable(true);
        
        moBoolWeightSourceAvailable.setEnabled(false);
        moDecWeightSource.setEditable(false);
        moDecWeightDestinyArrival.setEditable(true);
        moDecWeightDestinyDeparture.setEditable(true);
        moDatetimeArrival.setEditable(true);
        moTextScaleOperatorArrival.setEditable(true);
        moDatetimeDeparture.setEditable(true);
        moTextScaleOperatorDeparture.setEditable(true);
        moTextNote.setEditable(true);
        moTextNote2.setEditable(true);
        
        moDecPackingFullQuantityArrival.setEditable(false);
        moDecPackingEmptyQuantityArrival.setEditable(false);
        moDecPackingFullQuantityDeparture.setEditable(mbIsPacking);
        moDecPackingEmptyQuantityDeparture.setEditable(mbIsPacking);
    }

    private void computeWeightNet() {
        if (moDecWeightDestinyDeparture.getValue() > 0 && (moDecPackingFullQuantityArrival.getValue() > 0 || moDecPackingFullQuantityDeparture.getValue() > 0)) {
            // tare - packing_net_weight / full_packing_net_quantity:
            double average = ((moDecWeightDestinyArrival.getValue() - moDecWeightDestinyDeparture.getValue()) -
                ((moDecPackingFullQuantityArrival.getValue() + moDecPackingEmptyQuantityArrival.getValue()) * moItem.getPackingWeight()) +
                ((moDecPackingFullQuantityDeparture.getValue() + moDecPackingEmptyQuantityDeparture.getValue()) * moItem.getPackingWeight())) /
                (moDecPackingFullQuantityArrival.getValue() - moDecPackingFullQuantityDeparture.getValue());
            if (average == Double.POSITIVE_INFINITY || average == Double.NEGATIVE_INFINITY) {
                moDecWeightAverage.setValue(0.0);
            }
            else {
                moDecWeightAverage.setValue(average);
            }
        }
        
        double weiPacArr = (moDecPackingFullQuantityArrival.getValue() + moDecPackingEmptyQuantityArrival.getValue()) * moItem.getPackingWeight();
        double weiPacDep = (moDecPackingFullQuantityDeparture.getValue() + moDecPackingEmptyQuantityDeparture.getValue()) * moItem.getPackingWeight();
        double weiPacNet = weiPacArr - weiPacDep;
        
        double weiGross = moDecWeightDestinyArrival.getValue() - moDecWeightDestinyDeparture.getValue();
        double weiNet = moDecWeightDestinyDeparture.getValue() == 0.0 ? 0.0 : weiGross - weiPacNet;
        
        moDecWeightDestinyNetComputed.setValue(weiNet);
    }

    private void getSeasonRegion() {
        mnSeasonId = 0;
        mnRegionId = 0;

        try {
            mnSeasonId = SSomUtils.getProperSeasonId(miClient.getSession(), moDatetimeArrival.getValue(), moKeyItem.getValue()[0], moKeyProducer.getValue()[0]);

            if (mnSeasonId != SLibConsts.UNDEFINED) {
                mnRegionId = SSomUtils.getProperRegionId(miClient.getSession(), mnSeasonId, moKeyItem.getValue()[0], moKeyProducer.getValue()[0]);
            }
        }
        catch (Exception e) {
             SLibUtils.showException(this, e);
        }
    }

    private void itemStateKeyProducer() {
        if (moKeyProducer.getSelectedIndex() <= 0) {
            moProducer = null;
        }
        else {
            moProducer = (SDbProducer) miClient.getSession().readRegistry(SModConsts.SU_PROD, moKeyProducer.getValue());
            moKeyInputSource.setValue(new int[] { moProducer.getFkInputSourceId() });
        }
    }

    private void itemStateKeyItem() {
        moItem = null;
        mbIsPacking = false;
        mbIsLaboratory = false;
        
        moDecPackingFullQuantityArrival.setValue(0d);
        moDecPackingEmptyQuantityArrival.setValue(0d);
        moDecPackingFullQuantityDeparture.setValue(0d);
        moDecPackingEmptyQuantityDeparture.setValue(0d);
        jlPackingFullQuantityArrivalUnits.setText("");
        jlPackingEmptyQuantityArrivalUnits.setText("");
        jlPackingFullQuantityDepartureUnits.setText("");
        jlPackingEmptyQuantityDepartureUnits.setText("");
        
        moDecPackingWeight.setValue(0d);
        moDecWeightAverage.setValue(0d);
        jlWeightAverageUnits.setText("");
        
        moDecPackingFullQuantityArrival.setEditable(false);
        moDecPackingEmptyQuantityArrival.setEditable(false);
        moDecPackingFullQuantityDeparture.setEditable(false);
        moDecPackingEmptyQuantityDeparture.setEditable(false);
        
        moKeyInputSource.removeAllItems();
        moKeyInputSource.setEnabled(false);

        if (moKeyItem.getSelectedIndex() > 0) {
            moItem = (SDbItem) miClient.getSession().readRegistry(SModConsts.SU_ITEM, moKeyItem.getValue());
            mbIsPacking = moItem.isPacking();
            mbIsLaboratory = moItem.isLaboratory();

            if (mbIsPacking) {
                jlPackingFullQuantityArrivalUnits.setText(moItem.getPackingName());
                jlPackingEmptyQuantityArrivalUnits.setText(moItem.getPackingName());
                jlPackingFullQuantityDepartureUnits.setText(moItem.getPackingName());
                jlPackingEmptyQuantityDepartureUnits.setText(moItem.getPackingName());
                
                jlWeightAverageUnits.setText(SSomConsts.KG + " / " + moItem.getPackingName());
                
                moDecPackingWeight.setValue(moItem.getPackingWeight());
            }

            miClient.getSession().populateCatalogue(moKeyInputSource, SModConsts.SU_INP_SRC, SLibConsts.UNDEFINED, new SGuiParams(moItem.getFkInputCategoryId()));
            moKeyInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
            jbSetDefaultInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);

            if (moProducer != null) {
                moKeyInputSource.setValue(new int[] { moProducer.getFkInputSourceId() });
            }
            
            enableFields();
        }
    }
    
    private void itemStateWeightSourceAvailable() {
        moDecWeightSource.setEditable(moBoolWeightSourceAvailable.getValue());
    }

    private void actionSetDefaultInputSource() {
        if (jbSetDefaultInputSource.isEnabled()) {
            try {
                moKeyInputSource.setValue(new int[] { moProducer.getFkInputSourceId() });
            }
            catch (Exception e){
                miClient.showMsgBoxError("No hay origenes disponibles");
            }
        }
    }
    
    @Override
    public void addAllListeners() {
        moKeyProducer.addItemListener(this);
        moKeyItem.addItemListener(this);
        moBoolWeightSourceAvailable.addItemListener(this);
        
        jbSetDefaultInputSource.addActionListener(this);
        
        moDecWeightSource.addFocusListener(this);
        moDecWeightDestinyArrival.addFocusListener(this);
        moDecWeightDestinyDeparture.addFocusListener(this);
        moDecPackingFullQuantityArrival.addFocusListener(this);
        moDecPackingEmptyQuantityArrival.addFocusListener(this);
        moDecPackingFullQuantityDeparture.addFocusListener(this);
        moDecPackingEmptyQuantityDeparture.addFocusListener(this);
    }

    @Override
    public void removeAllListeners() {
        moKeyProducer.removeItemListener(this);
        moKeyItem.removeItemListener(this);
        moBoolWeightSourceAvailable.removeItemListener(this);
        
        jbSetDefaultInputSource.removeActionListener(this);
        
        moDecWeightSource.removeFocusListener(this);
        moDecWeightDestinyArrival.removeFocusListener(this);
        moDecWeightDestinyDeparture.removeFocusListener(this);
        moDecPackingFullQuantityArrival.removeFocusListener(this);
        moDecPackingEmptyQuantityArrival.removeFocusListener(this);
        moDecPackingFullQuantityDeparture.removeFocusListener(this);
        moDecPackingEmptyQuantityDeparture.removeFocusListener(this);
    }

    @Override
    public void reloadCatalogues() {
        try {
            SGuiParams params = new SGuiParams();
            params.getParamsMap().put(SModConsts.SX_ITEM_ALT, SSomUtils.getAlternativeItemCodes(miClient.getSession()));
            miClient.getSession().populateCatalogue(moKeyScale, SModConsts.CU_USR_SCA, SLibConsts.UNDEFINED, new SGuiParams(new int[] { miClient.getSession().getUser().getPkUserId() }));
            miClient.getSession().populateCatalogue(moKeyItem, SModConsts.SU_ITEM, SLibConsts.UNDEFINED, params);
            miClient.getSession().populateCatalogue(moKeyProducer, SModConsts.SU_PROD, SLibConsts.UNDEFINED, null);
            
            arrWeiChgIds = SSomUtils.getAlternativeItemWeigthChangeCodes(miClient.getSession()).split(";");
        }
        catch (Exception e) {
            miClient.showMsgBoxError(e.getMessage());
        }
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbTicketAlternative) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;
        
        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            // switch between combobox and text field for scalse:
            
            moKeyScale.setVisible(true);
            jtfScale.setVisible(false);
            jtfScale.setText("");
            
            // prepare registry creation:
            
            moRegistry.initPrimaryKey();
            moRegistry.setDatetimeArrival(miClient.getSession().getWorkingDate());
            moRegistry.setDatetimeDeparture(miClient.getSession().getWorkingDate());
            moRegistry.setWeightSourceAvailable(true);
            moRegistry.setFkTicketStatusId(SModSysConsts.SS_TIC_ST_SCA);
            moRegistry.setFkExwFacilityOriginId(SModSysConsts.MU_EXW_FAC_NA);
            moRegistry.setFkExwFacilityDestinationId(SModSysConsts.MU_EXW_FAC_NA);
            
            jtfRegistryKey.setText("");
        }
        else {
            // switch between combobox and text field for scalse:
            
            moKeyScale.setVisible(false);
            jtfScale.setVisible(true);
            jtfScale.setText(moRegistry.getXtaScaleName());
            
            // prepare registry edition:
            
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moKeyScale.setValue(new int[] { moRegistry.getFkScaleId() });
        moBoolTared.setValue(moRegistry.isTared());
        moTextTicket.setValue(moRegistry.getNumber());
        
        moKeyProducer.setValue(new int[] { moRegistry.getFkProducerId() });
        itemStateKeyProducer();
        
        moKeyItem.setValue(new int[] { moRegistry.getFkItemId() });
        itemStateKeyItem();
        
        if (moRegistry.getFkInputSourceId() == SModSysConsts.SU_INP_SRC_NA) {
            moKeyInputSource.resetField();
        }
        else {
            moKeyInputSource.setValue(new int[] { moRegistry.getFkInputSourceId() });
        }
        
        moTextPlates.setValue(moRegistry.getPlate());
        moTextPlatesCage.setValue(moRegistry.getPlateCage());
        moTextDriver.setValue(moRegistry.getDriver());
        moDecWeightSource.setValue(moRegistry.getWeightSource());
        moBoolWeightSourceAvailable.setValue(moRegistry.isWeightSourceAvailable());
        moDecWeightDestinyArrival.setValue(moRegistry.getWeightDestinyArrival());
        moDecWeightDestinyDeparture.setValue(moRegistry.getWeightDestinyDeparture());
        moDatetimeArrival.setValue(moRegistry.getDatetimeArrival());
        moDatetimeDeparture.setValue(moRegistry.getDatetimeDeparture());
        moTextScaleOperatorArrival.setValue(moRegistry.getScaleOperatorArrival());
        moTextScaleOperatorDeparture.setValue(moRegistry.getScaleOperatorDeparture());
        moDecPackingFullQuantityArrival.setValue(moRegistry.getPackingFullQuantityArrival());
        moDecPackingEmptyQuantityArrival.setValue(moRegistry.getPackingEmptyQuantityArrival());
        moDecPackingFullQuantityDeparture.setValue(moRegistry.getPackingFullQuantityDeparture());
        moDecPackingEmptyQuantityDeparture.setValue(moRegistry.getPackingEmptyQuantityDeparture());
        moDecWeightDestinyNet.setValue(moRegistry.getWeightDestinyNet_r());
        moTextNote.setValue(moRegistry.getScaleCommentsArrival());
        moTextNote2.setValue(moRegistry.getScaleCommentsDeparture());

        mbIsRevImport1 = moRegistry.isRevueltaImport1();
        mbIsRevImport2 = moRegistry.isRevueltaImport2();

        setFormEditable(true);

        if (moRegistry.isRegistryNew()) {
            if (moKeyScale.getItemCount() == 2) {
                moKeyScale.setSelectedIndex(1);
            }
        }
        else {

        }
        
        moKeyInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
        moDecWeightAverage.setEditable(false);

        itemStateWeightSourceAvailable();
        computeWeightNet();
        
        enableFields();

        addAllListeners();
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        SDbTicketAlternative registry = moRegistry.clone();

        if (registry.isRegistryNew()) {
            // nothing to do by now
        }

        getSeasonRegion();

        registry.setNumber(moTextTicket.getValue());
        registry.setDate(moDatetimeArrival.getValue());
        //registry.setQuantity(...); // seemingly unused
        registry.setPlate(moTextPlates.getValue());
        registry.setPlateCage(moTextPlatesCage.getValue());
        registry.setDriver(moTextDriver.getValue());
        registry.setDatetimeArrival(moDatetimeArrival.getValue());
        registry.setDatetimeDeparture(moRegistry.isRegistryNew() ? moDatetimeArrival.getValue() : moDatetimeDeparture.getValue());
        
        registry.setPackingFullQuantityArrival(moDecPackingFullQuantityArrival.getValue());
        registry.setPackingEmptyQuantityArrival(moDecPackingEmptyQuantityArrival.getValue());
        
        registry.setWeightSource(moDecWeightSource.getValue());
        registry.setWeightDestinyArrival(moDecWeightDestinyArrival.getValue());
        registry.setScaleOperatorArrival(moTextScaleOperatorArrival.getValue());
        registry.setScaleOperatorDeparture(moTextScaleOperatorDeparture.getValue());
        registry.setScaleCommentsArrival(moTextNote.getValue());
        registry.setScaleCommentsDeparture(moTextNote2.getValue());
        
        boolean tared = mnFormSubtype == SModConsts.SX_TIC_TARE_PEND || moRegistry.isTared();
        
        if (tared) {
            registry.setPackingFullQuantityDeparture(moDecPackingFullQuantityDeparture.getValue());
            registry.setPackingEmptyQuantityDeparture(moDecPackingEmptyQuantityDeparture.getValue());
            
            registry.setWeightDestinyDeparture(moDecWeightDestinyDeparture.getValue());
        }
        else {
            registry.setPackingFullQuantityDeparture(0);
            registry.setPackingEmptyQuantityDeparture(0);
            
            registry.setWeightDestinyDeparture(0);
        }
        
        //registry.setWeightDestinyGross_r(...);
        registry.setWeightDestinyNet_r(moDecWeightDestinyNetComputed.getValue());
        //registry.setSystemPenaltyPercentage(...);
        //registry.setSystemWeightPayment(...);
        //registry.setSystemPricePerTon(...);
        //registry.setSystemPayment_r(...);
        //registry.setSystemFreight(...);
        //registry.setSystemTotal_r(...);
        //registry.setUserPenaltyPercentage(...);
        //registry.setUserWeightPayment(...);
        //registry.setUserPricePerTon(...);
        //registry.setUserPayment_r(...);
        //registry.setUserFreight(...);
        //registry.setUserTotal_r(...);
        //registry.setDpsSupplyDate_n(...);
        registry.setRequiredFreight("N");
        registry.setRevueltaImport1(mbIsRevImport1);
        registry.setRevueltaImport2(mbIsRevImport2);
        registry.setWeightSourceAvailable(moBoolWeightSourceAvailable.getValue());
        registry.setMfgOutsourcing(false);
        registry.setTared(tared);
        registry.setPayed(false);
        registry.setAssorted(false);
        registry.setPacking(mbIsPacking);
        registry.setLaboratory(mbIsLaboratory);
        registry.setDpsSupply(false);
        //registry.setDeleted(...);
        //registry.setSystem(...);
        registry.setFkScaleId(moKeyScale.isVisible() ? moKeyScale.getValue()[0] : registry.getFkScaleId());
        registry.setFkTicketStatusId(registry.isRegistryNew() ? SModSysConsts.SS_TIC_ST_SCA : registry.getFkTicketStatusId());
        registry.setFkSeasonId_n(mnSeasonId);
        registry.setFkRegionId_n(mnRegionId);
        registry.setFkItemId(moKeyItem.getValue()[0]);
        registry.setFkUnitId(moKeyItem.getSelectedItem().getForeignKey()[0]);
        registry.setFkProducerId(moKeyProducer.getValue()[0]);
        registry.setFkInputSourceId(!moKeyInputSource.isEnabled() ? SModSysConsts.SU_INP_SRC_NA : moKeyInputSource.getValue()[0]);
        registry.setFkLaboratoryId_n(registry.isRegistryNew() ? 0 : registry.getFkLaboratoryId_n());
        //registry.setFkExternalDpsYearId_n(...);
        //registry.setFkExternalDpsDocId_n(...);
        //registry.setFkExternalDpsEntryId_n(...);
        //registry.setFkUserTaredId(miClient.getSession().getUser().getPkUserId());
        //registry.setFkUserPayedId(...);
        //registry.setFkUserAssortedId(...);
        
        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();
        
        if (validation.isValid()) {
            if (!SGuiClientUtils.isPeriodOpened(miClient.getSession(), moDatetimeArrival.getValue())) {
                validation.setMessage("El período está cerrado.");
                validation.setComponent(((JSpinner.DefaultEditor) moDatetimeArrival.getComponent().getEditor()).getTextField());
            }
            else {
                if (mnFormSubtype == SModConsts.SX_TIC_TARE_PEND) {
                    if (moKeyInputSource.getItemCount() > 1 && moKeyInputSource.getSelectedIndex() <= 0) {
                        validation.setMessage(SGuiConsts.ERR_MSG_FIELD_REQ + "'" + moKeyInputSource.getFieldName() + "'." +
                                (moKeyInputSource.isEnabled() ? "" : "Favor de modificar este registro desde la vista 'Boletos báscula'."));
                        if (moKeyInputSource.isEnabled()) {
                            validation.setComponent(moKeyInputSource);
                        }
                    }
                    
                    if (validation.isValid() && !mbIsRevImport2) {
                        validation = SGuiUtils.validateDateRange(moDatetimeArrival, moDatetimeDeparture);
                        if (!validation.isValid()) {
                            if (moDatetimeArrival.isEditable()) {
                                validation.setComponent(((JSpinner.DefaultEditor) moDatetimeArrival.getComponent().getEditor()).getTextField());
                            }
                            else if (moDatetimeDeparture.isEditable()) {
                                validation.setComponent(((JSpinner.DefaultEditor) moDatetimeDeparture.getComponent().getEditor()).getTextField());
                            }
                        }
                    }
                }

                if (validation.isValid() && mbIsPacking) {
                    if (moDecPackingFullQuantityArrival.getValue() == 0 &&
                            miClient.showMsgBoxConfirm("No se ha especificado un valor para el campo '" + moDecPackingFullQuantityArrival.getFieldName() + "'."
                                    + "\n" + SGuiConsts.MSG_CNF_CONT_OMIT_VAL) != JOptionPane.YES_OPTION) {
                        validation.setMessage(SGuiConsts.ERR_MSG_FIELD_REQ + "'" + moDecPackingFullQuantityArrival.getFieldName() + "'.");
                        validation.setComponent(moDecPackingFullQuantityArrival);
                    }
                    else if (mnFormSubtype == SModConsts.SX_TIC_TARE_PEND && moDecPackingEmptyQuantityDeparture.isEditable() && moDecPackingEmptyQuantityDeparture.getValue() == 0 &&
                            miClient.showMsgBoxConfirm("No se ha especificado un valor para el campo '" + moDecPackingEmptyQuantityDeparture.getFieldName() + "'."
                                    + "\n" + SGuiConsts.MSG_CNF_CONT_OMIT_VAL) != JOptionPane.YES_OPTION) {
                        validation.setMessage(SGuiConsts.ERR_MSG_FIELD_REQ + "'" + moDecPackingEmptyQuantityDeparture.getFieldName() + "'.");
                        validation.setComponent(moDecPackingEmptyQuantityDeparture);
                    }
                }
                
                computeWeightNet();
                        
                boolean weiChg = false;
                for (String id : arrWeiChgIds) {
                    if (SLibUtilities.parseInt(id) == moKeyItem.getValue()[0]) {
                        weiChg = true;
                    }
                }
                
                if (validation.isValid() && !weiChg) {
                    if (!SLibUtils.compareAmount(moDecWeightDestinyNetComputed.getValue(), moDecWeightDestinyNet.getValue())) {
                        validation.setMessage("El valor de los campos '" + moDecWeightDestinyNetComputed.getFieldName() + "' y '" + moDecWeightDestinyNet.getFieldName() + "' no coincide.");
                    }
                } 
            }
        }

        return validation;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();

            if (button == jbSetDefaultInputSource) {
                actionSetDefaultInputSource();
            }
        }
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof JComboBox && e.getStateChange() == ItemEvent.SELECTED) {
            JComboBox comboBox = (JComboBox) e.getSource();

            if (comboBox == moKeyItem) {
                itemStateKeyItem();
            }
            else if (comboBox == moKeyProducer) {
                itemStateKeyProducer();
            }
        }
        else if (e.getSource() instanceof JCheckBox) {
            JCheckBox checkBox = (JCheckBox)  e.getSource();

            if (checkBox == moBoolWeightSourceAvailable) {
                itemStateWeightSourceAvailable();
            }
        }
    }

    @Override
    public void focusGained(FocusEvent e) {

    }

    @Override
    public void focusLost(FocusEvent e) {
        if (e.getSource() instanceof javax.swing.JTextField) {
            JTextField textField = (JTextField) e.getSource();

            if (textField == moDecWeightSource.getComponent() ||
                textField == moDecWeightDestinyArrival.getComponent() ||
                textField == moDecWeightDestinyDeparture.getComponent() ||
                textField == moDecPackingFullQuantityArrival.getComponent() ||
                textField == moDecPackingEmptyQuantityArrival.getComponent() ||
                textField == moDecPackingFullQuantityDeparture.getComponent() ||
                textField == moDecPackingEmptyQuantityDeparture.getComponent()) {

                computeWeightNet();
            }
        }
    }
}
