/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package som.mod.som.form;

import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import som.mod.SModConsts;
import som.mod.SModSysConsts;
import som.mod.som.db.SDbInputCategory;

/**
 *
 * @author Sergio Flores, Isabel Servín
 */
public class SFormInputCategory extends sa.lib.gui.bean.SBeanForm {

    private SDbInputCategory moRegistry;

    /**
     * Creates new form SFormInputClass
     * @param client
     * @param title
     */
    public SFormInputCategory(SGuiClient client, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.SU_INP_CT, SLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        moTextCode = new sa.lib.gui.bean.SBeanFieldText();
        jPanel5 = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        moTextName = new sa.lib.gui.bean.SBeanFieldText();
        jPanel6 = new javax.swing.JPanel();
        jlFreReq = new javax.swing.JLabel();
        moKeyFreReq = new sa.lib.gui.bean.SBeanFieldKey();
        jlReqFreHelp = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jchWarehouseRequired = new javax.swing.JCheckBox();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCode.setText("Código:*");
        jlCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlCode);

        moTextCode.setText("sBeanFieldText1");
        jPanel4.add(moTextCode);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlName.setText("Nombre:*");
        jlName.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jlName);

        moTextName.setText("sBeanFieldText1");
        moTextName.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel5.add(moTextName);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlFreReq.setText("Control fletes:*");
        jlFreReq.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel6.add(jlFreReq);

        moKeyFreReq.setEditable(true);
        moKeyFreReq.setPreferredSize(new java.awt.Dimension(120, 23));
        jPanel6.add(moKeyFreReq);

        jlReqFreHelp.setForeground(new java.awt.Color(109, 109, 109));
        jlReqFreHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlReqFreHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_view_info.png"))); // NOI18N
        jlReqFreHelp.setToolTipText("Habilita el control de fletes en la captura de boletos de báscula de los insumos de esta categoría");
        jlReqFreHelp.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel6.add(jlReqFreHelp);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jchWarehouseRequired.setText("Almacén de descarga requerido");
        jchWarehouseRequired.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel7.add(jchWarehouseRequired);

        jPanel2.add(jPanel7);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JCheckBox jchWarehouseRequired;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlFreReq;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlReqFreHelp;
    private sa.lib.gui.bean.SBeanFieldKey moKeyFreReq;
    private sa.lib.gui.bean.SBeanFieldText moTextCode;
    private sa.lib.gui.bean.SBeanFieldText moTextName;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 480, 300);

        moTextCode.setTextSettings(SGuiUtils.getLabelName(jlCode), 5);
        moTextName.setTextSettings(SGuiUtils.getLabelName(jlName), 50);
        moKeyFreReq.setKeySettings(miClient, SGuiUtils.getLabelName(jlFreReq), true);

        moFields.addField(moTextCode);
        moFields.addField(moTextName);
        moFields.addField(moKeyFreReq);

        moFields.setFormButton(jbSave);
    }

    @Override
    public void addAllListeners() {

    }

    @Override
    public void removeAllListeners() {

    }

    @Override
    @SuppressWarnings("unchecked")
    public void reloadCatalogues() {
        moKeyFreReq.removeAllItems();
        SModSysConsts.SX_REQ_FRE_OPTIONS.forEach((item) -> {
            moKeyFreReq.addItem(item);
        });
        moKeyFreReq.setSelectedIndex(0);
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbInputCategory) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            moRegistry.initPrimaryKey();
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moTextName.setValue(moRegistry.getName());
        moTextCode.setValue(moRegistry.getCode());
        jchWarehouseRequired.setSelected(moRegistry.isWareouseUnloadRequired());
        
        for (int i = 1; i <= SModSysConsts.SX_REQ_FRE_CODE.size(); i++) {
            if (SModSysConsts.SX_REQ_FRE_CODE.get(i).equals(moRegistry.getRequiredFreight())) {
                moKeyFreReq.setValue(new int[] { i });
            }
        }

        setFormEditable(true);

        addAllListeners();
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        SDbInputCategory registry = moRegistry.clone();

        if (registry.isRegistryNew()) { }

        registry.setName(moTextName.getValue());
        registry.setCode(moTextCode.getValue());
        registry.setRequiredFreight(SModSysConsts.SX_REQ_FRE_CODE.get(moKeyFreReq.getValue()[0]));
        registry.setWareouseUnloadRequired(jchWarehouseRequired.isSelected());

        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();

        return validation;
    }
}
