/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package som.mod.som.form;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiItem;
import sa.lib.gui.SGuiParams;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanForm;
import som.gui.SGuiClientUtils;
import som.mod.SModConsts;
import som.mod.SModSysConsts;
import som.mod.som.db.SDbItem;
import som.mod.som.db.SDbProducer;
import som.mod.som.db.SDbTicket;
import som.mod.som.db.SDbTicketNote;
import som.mod.som.db.SSomConsts;
import som.mod.som.db.SSomUtils;

/**
 *
 * @author Juan Barajas, Alfredo Pérez, Sergio Flores, Isabel Servín, Sergio Flores
 */
public class SFormTicket extends SBeanForm implements ActionListener, ItemListener, FocusListener, ChangeListener {

    private Connection moConnectionRevuelta;

    private SDbTicket moRegistry;
    private SDbItem moItem;
    private SDbProducer moProducer;
    private int mnSeasonId;
    private int mnRegionId;
    private boolean mbIsPacking;
    private boolean mbIsLaboratory;
    private boolean mbIsSaveSend;
    private boolean mbIsRevImport1;
    private boolean mbIsRevImport2;

    private boolean mbFirstTime;
    private JButton jbSaveSend;
    
    private String msComentArr;
    private String msComentDep;

    /**
     * Creates new form SFormTicket
     * @param client GUI client.
     * @param title Form title.
     * @param formSubType Form subtype: 1) normal ticket: SLibConsts.UNDEFINED; 2) ticket to be tared: SModConsts.SX_TIC_TARE_PEND.
     */
    public SFormTicket(SGuiClient client, String title, int formSubType) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.S_TIC, formSubType, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jlScale = new javax.swing.JLabel();
        moKeyScale = new sa.lib.gui.bean.SBeanFieldKey();
        moTextScale = new sa.lib.gui.bean.SBeanFieldText();
        moBoolTared = new sa.lib.gui.bean.SBeanFieldBoolean();
        jPanel4 = new javax.swing.JPanel();
        jlTicket = new javax.swing.JLabel();
        moTextTicket = new sa.lib.gui.bean.SBeanFieldText();
        jlDummy = new javax.swing.JLabel();
        jbImportTicket = new javax.swing.JButton();
        jbCleanTicket = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jlProducer = new javax.swing.JLabel();
        moKeyProducer = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel12 = new javax.swing.JPanel();
        jlItem = new javax.swing.JLabel();
        moKeyItem = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel21 = new javax.swing.JPanel();
        jlInputSource = new javax.swing.JLabel();
        moKeyInputSource = new sa.lib.gui.bean.SBeanFieldKey();
        jbInputSource = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jlRegion = new javax.swing.JLabel();
        moKeyRegion = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel6 = new javax.swing.JPanel();
        jlPlates = new javax.swing.JLabel();
        moTextPlates = new sa.lib.gui.bean.SBeanFieldText();
        jlPlatesCage = new javax.swing.JLabel();
        moTextPlatesCage = new sa.lib.gui.bean.SBeanFieldText();
        jPanel3 = new javax.swing.JPanel();
        jlDriver = new javax.swing.JLabel();
        moTextDriver = new sa.lib.gui.bean.SBeanFieldText();
        jPanel7 = new javax.swing.JPanel();
        jlWeightSource = new javax.swing.JLabel();
        moDecWeightSource = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightSourceUnit = new javax.swing.JLabel();
        moBoolWeightSourceAvailable = new sa.lib.gui.bean.SBeanFieldBoolean();
        jPanel9 = new javax.swing.JPanel();
        jlWeightDestinyArrival = new javax.swing.JLabel();
        moDecWeightDestinyArrival = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightDestinyArrivalUnit = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jlWeightDestinyDeparture = new javax.swing.JLabel();
        moDecWeightDestinyDeparture = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightDestinyDepartureUnit = new javax.swing.JLabel();
        jbImportTareTicket = new javax.swing.JButton();
        jbCleanTare = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jlDatetimeArrival = new javax.swing.JLabel();
        moDatetimeArrival = new sa.lib.gui.bean.SBeanFieldDatetime();
        jLabel1 = new javax.swing.JLabel();
        jlOpeArr = new javax.swing.JLabel();
        moTextOpeArr = new sa.lib.gui.bean.SBeanFieldText();
        jPanel11 = new javax.swing.JPanel();
        jlDatetimeDeparture = new javax.swing.JLabel();
        moDatetimeDeparture = new sa.lib.gui.bean.SBeanFieldDatetime();
        jLabel2 = new javax.swing.JLabel();
        jlOpeDep = new javax.swing.JLabel();
        moTextOpeDep = new sa.lib.gui.bean.SBeanFieldText();
        jPanel16 = new javax.swing.JPanel();
        jlPackingFullQuantityArrival = new javax.swing.JLabel();
        moDecPackingFullQuantityArrival = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingFullQuantityArrivalUnit = new javax.swing.JLabel();
        jbPackingFullQuantityArrival = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jlPackingEmptyQuantityArrival = new javax.swing.JLabel();
        moDecPackingEmptyQuantityArrival = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingEmptyQuantityArrivalUnit = new javax.swing.JLabel();
        jbPackingEmptyQuantityArrival = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jlPackingFullQuantityDeparture = new javax.swing.JLabel();
        moDecPackingFullQuantityDeparture = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingFullQuantityDepartureUnit = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jlPackingEmptyQuantityDeparture = new javax.swing.JLabel();
        moDecPackingEmptyQuantityDeparture = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlPackingEmptyQuantityDepartureUnit = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jlWeightAverage = new javax.swing.JLabel();
        moDecWeightAverage = new sa.lib.gui.bean.SBeanFieldDecimal();
        jlWeightAverageUnit = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlNote = new javax.swing.JLabel();
        moTextNote = new sa.lib.gui.bean.SBeanFieldText();
        jPanel14 = new javax.swing.JPanel();
        jlTicOrig = new javax.swing.JLabel();
        moKeyTicOrig = new sa.lib.gui.bean.SBeanFieldKey();
        jlPackingFullQuantityDepartureUnit1 = new javax.swing.JLabel();
        moRadFreight = new sa.lib.gui.bean.SBeanFieldRadio();
        jlPackingFullQuantityDepartureUnit3 = new javax.swing.JLabel();
        jlFreightOrigin = new javax.swing.JLabel();
        moKeyFreightOrigin = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel22 = new javax.swing.JPanel();
        jlTicDest = new javax.swing.JLabel();
        moKeyTicDest = new sa.lib.gui.bean.SBeanFieldKey();
        jlPackingFullQuantityDepartureUnit2 = new javax.swing.JLabel();
        moRadDependent = new sa.lib.gui.bean.SBeanFieldRadio();
        jlPackingFullQuantityDepartureUnit4 = new javax.swing.JLabel();
        jlTicFreight = new javax.swing.JLabel();
        moKeyTicFreight = new sa.lib.gui.bean.SBeanFieldKey();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(20, 1, 0, 5));

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlScale.setForeground(new java.awt.Color(51, 51, 255));
        jlScale.setText("Báscula:*");
        jlScale.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel13.add(jlScale);

        moKeyScale.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel13.add(moKeyScale);

        moTextScale.setEditable(false);
        moTextScale.setText("sBeanFieldText1");
        moTextScale.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel13.add(moTextScale);

        moBoolTared.setText("Boleto tarado");
        moBoolTared.setEditable(false);
        moBoolTared.setPreferredSize(new java.awt.Dimension(115, 23));
        jPanel13.add(moBoolTared);

        jPanel2.add(jPanel13);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTicket.setText("Boleto:*");
        jlTicket.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel4.add(jlTicket);
        jPanel4.add(moTextTicket);

        jlDummy.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel4.add(jlDummy);

        jbImportTicket.setText("Importar de Revuelta");
        jbImportTicket.setToolTipText("Importar de Revuelta (primer pesada)");
        jbImportTicket.setPreferredSize(new java.awt.Dimension(165, 23));
        jPanel4.add(jbImportTicket);

        jbCleanTicket.setText("Limpiar");
        jbCleanTicket.setToolTipText("Limpiar datos primer pesada");
        jbCleanTicket.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel4.add(jbCleanTicket);

        jPanel2.add(jPanel4);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlProducer.setText("Proveedor:*");
        jlProducer.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel10.add(jlProducer);

        moKeyProducer.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel10.add(moKeyProducer);

        jPanel2.add(jPanel10);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlItem.setText("Ítem:*");
        jlItem.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel12.add(jlItem);

        moKeyItem.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel12.add(moKeyItem);

        jPanel2.add(jPanel12);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlInputSource.setText("Origen insumo:*");
        jlInputSource.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel21.add(jlInputSource);

        moKeyInputSource.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel21.add(moKeyInputSource);

        jbInputSource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_wizard.gif"))); // NOI18N
        jbInputSource.setToolTipText("Seleccionar origen insumo del proveedor");
        jbInputSource.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel21.add(jbInputSource);

        jLabel6.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel21.add(jLabel6);

        jlRegion.setText("Región:*");
        jlRegion.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel21.add(jlRegion);

        moKeyRegion.setPreferredSize(new java.awt.Dimension(202, 23));
        jPanel21.add(moKeyRegion);

        jPanel2.add(jPanel21);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPlates.setText("Placas vehículo:*");
        jlPlates.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel6.add(jlPlates);

        moTextPlates.setText("sBeanFieldText2");
        jPanel6.add(moTextPlates);

        jlPlatesCage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPlatesCage.setText("Placas caja:");
        jlPlatesCage.setPreferredSize(new java.awt.Dimension(90, 23));
        jPanel6.add(jlPlatesCage);

        moTextPlatesCage.setText("sBeanFieldText2");
        jPanel6.add(moTextPlatesCage);

        jPanel2.add(jPanel6);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDriver.setText("Chofer vehículo:*");
        jlDriver.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel3.add(jlDriver);

        moTextDriver.setText("sBeanFieldText2");
        moTextDriver.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel3.add(moTextDriver);

        jPanel2.add(jPanel3);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightSource.setText("Peso origen:*");
        jlWeightSource.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel7.add(jlWeightSource);
        jPanel7.add(moDecWeightSource);

        jlWeightSourceUnit.setText("UNIT");
        jlWeightSourceUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel7.add(jlWeightSourceUnit);

        moBoolWeightSourceAvailable.setText("Peso origen disponible");
        moBoolWeightSourceAvailable.setPreferredSize(new java.awt.Dimension(165, 23));
        jPanel7.add(moBoolWeightSourceAvailable);

        jPanel2.add(jPanel7);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightDestinyArrival.setText("Peso entrada:*");
        jlWeightDestinyArrival.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel9.add(jlWeightDestinyArrival);
        jPanel9.add(moDecWeightDestinyArrival);

        jlWeightDestinyArrivalUnit.setText("UNIT");
        jlWeightDestinyArrivalUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel9.add(jlWeightDestinyArrivalUnit);

        jPanel2.add(jPanel9);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightDestinyDeparture.setText("Peso salida:*");
        jlWeightDestinyDeparture.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel15.add(jlWeightDestinyDeparture);
        jPanel15.add(moDecWeightDestinyDeparture);

        jlWeightDestinyDepartureUnit.setText("UNIT");
        jlWeightDestinyDepartureUnit.setPreferredSize(new java.awt.Dimension(35, 23));
        jPanel15.add(jlWeightDestinyDepartureUnit);

        jbImportTareTicket.setText("Importar de Revuelta");
        jbImportTareTicket.setToolTipText("Importar de Revuelta (segunda pesada)");
        jbImportTareTicket.setPreferredSize(new java.awt.Dimension(165, 23));
        jPanel15.add(jbImportTareTicket);

        jbCleanTare.setText("Limpiar");
        jbCleanTare.setToolTipText("Limpiar datos segunda pesada");
        jbCleanTare.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel15.add(jbCleanTare);

        jPanel2.add(jPanel15);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDatetimeArrival.setText("Fecha-hora entrada:*");
        jlDatetimeArrival.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel8.add(jlDatetimeArrival);
        jPanel8.add(moDatetimeArrival);

        jLabel1.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel8.add(jLabel1);

        jlOpeArr.setText("Operador báscula entrada:");
        jlOpeArr.setPreferredSize(new java.awt.Dimension(155, 23));
        jPanel8.add(jlOpeArr);

        moTextOpeArr.setText("sBeanFieldText2");
        moTextOpeArr.setPreferredSize(new java.awt.Dimension(260, 23));
        jPanel8.add(moTextOpeArr);

        jPanel2.add(jPanel8);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDatetimeDeparture.setText("Fecha-hora salida:*");
        jlDatetimeDeparture.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel11.add(jlDatetimeDeparture);
        jPanel11.add(moDatetimeDeparture);

        jLabel2.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel11.add(jLabel2);

        jlOpeDep.setText("Operador báscula salida:");
        jlOpeDep.setPreferredSize(new java.awt.Dimension(155, 23));
        jPanel11.add(jlOpeDep);

        moTextOpeDep.setText("sBeanFieldText2");
        moTextOpeDep.setPreferredSize(new java.awt.Dimension(260, 23));
        jPanel11.add(moTextOpeDep);

        jPanel2.add(jPanel11);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPackingFullQuantityArrival.setText("Cant. empaque lleno entrada:");
        jlPackingFullQuantityArrival.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel16.add(jlPackingFullQuantityArrival);
        jPanel16.add(moDecPackingFullQuantityArrival);

        jlPackingFullQuantityArrivalUnit.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel16.add(jlPackingFullQuantityArrivalUnit);

        jbPackingFullQuantityArrival.setText("Modificar");
        jbPackingFullQuantityArrival.setToolTipText("Modificar cantidad empaque lleno");
        jbPackingFullQuantityArrival.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbPackingFullQuantityArrival.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel16.add(jbPackingFullQuantityArrival);

        jPanel2.add(jPanel16);

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPackingEmptyQuantityArrival.setText("Cant. empaque vacío entrada:");
        jlPackingEmptyQuantityArrival.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel18.add(jlPackingEmptyQuantityArrival);
        jPanel18.add(moDecPackingEmptyQuantityArrival);

        jlPackingEmptyQuantityArrivalUnit.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel18.add(jlPackingEmptyQuantityArrivalUnit);

        jbPackingEmptyQuantityArrival.setText("Modificar");
        jbPackingEmptyQuantityArrival.setToolTipText("Modificar cantidad empaque vacío");
        jbPackingEmptyQuantityArrival.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbPackingEmptyQuantityArrival.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel18.add(jbPackingEmptyQuantityArrival);

        jPanel2.add(jPanel18);

        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPackingFullQuantityDeparture.setText("Cant. empaque lleno salida:");
        jlPackingFullQuantityDeparture.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel17.add(jlPackingFullQuantityDeparture);
        jPanel17.add(moDecPackingFullQuantityDeparture);

        jlPackingFullQuantityDepartureUnit.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel17.add(jlPackingFullQuantityDepartureUnit);

        jPanel2.add(jPanel17);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlPackingEmptyQuantityDeparture.setText("Cant. empaque vacío salida:");
        jlPackingEmptyQuantityDeparture.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel19.add(jlPackingEmptyQuantityDeparture);
        jPanel19.add(moDecPackingEmptyQuantityDeparture);

        jlPackingEmptyQuantityDepartureUnit.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel19.add(jlPackingEmptyQuantityDepartureUnit);

        jPanel2.add(jPanel19);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlWeightAverage.setText("Peso promedio:");
        jlWeightAverage.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel20.add(jlWeightAverage);
        jPanel20.add(moDecWeightAverage);

        jlWeightAverageUnit.setPreferredSize(new java.awt.Dimension(50, 23));
        jPanel20.add(jlWeightAverageUnit);

        jPanel2.add(jPanel20);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlNote.setText("Observaciones entrada:");
        jlNote.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel5.add(jlNote);

        moTextNote.setText("sBeanFieldText2");
        moTextNote.setPreferredSize(new java.awt.Dimension(600, 23));
        jPanel5.add(moTextNote);

        jPanel2.add(jPanel5);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTicOrig.setText("Procedencia boleto:*");
        jlTicOrig.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel14.add(jlTicOrig);

        moKeyTicOrig.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel14.add(moKeyTicOrig);

        jlPackingFullQuantityDepartureUnit1.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel14.add(jlPackingFullQuantityDepartureUnit1);

        buttonGroup1.add(moRadFreight);
        moRadFreight.setText("El boleto representa un flete");
        moRadFreight.setPreferredSize(new java.awt.Dimension(230, 23));
        jPanel14.add(moRadFreight);

        jlPackingFullQuantityDepartureUnit3.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel14.add(jlPackingFullQuantityDepartureUnit3);

        jlFreightOrigin.setText("Origen flete:*");
        jlFreightOrigin.setPreferredSize(new java.awt.Dimension(85, 23));
        jPanel14.add(jlFreightOrigin);

        moKeyFreightOrigin.setEnabled(false);
        moKeyFreightOrigin.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel14.add(moKeyFreightOrigin);

        jPanel2.add(jPanel14);

        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTicDest.setText("Destino boleto:*");
        jlTicDest.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel22.add(jlTicDest);

        moKeyTicDest.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel22.add(moKeyTicDest);

        jlPackingFullQuantityDepartureUnit2.setPreferredSize(new java.awt.Dimension(25, 23));
        jPanel22.add(jlPackingFullQuantityDepartureUnit2);

        buttonGroup1.add(moRadDependent);
        moRadDependent.setText("El boleto depende de otro con flete");
        moRadDependent.setPreferredSize(new java.awt.Dimension(230, 23));
        jPanel22.add(moRadDependent);

        jlPackingFullQuantityDepartureUnit4.setPreferredSize(new java.awt.Dimension(5, 23));
        jPanel22.add(jlPackingFullQuantityDepartureUnit4);

        jlTicFreight.setText("Boleto flete:*");
        jlTicFreight.setPreferredSize(new java.awt.Dimension(85, 23));
        jPanel22.add(jlTicFreight);

        moKeyTicFreight.setEnabled(false);
        moKeyTicFreight.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel22.add(moKeyTicFreight);

        jPanel2.add(jPanel22);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            handleWindowActivated();
        }
        catch (InstantiationException | IllegalAccessException e) {
            SLibUtils.printException(this, e);
            Logger.getLogger(SFormTicket.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        attendWindowClosed();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbCleanTare;
    private javax.swing.JButton jbCleanTicket;
    private javax.swing.JButton jbImportTareTicket;
    private javax.swing.JButton jbImportTicket;
    private javax.swing.JButton jbInputSource;
    private javax.swing.JButton jbPackingEmptyQuantityArrival;
    private javax.swing.JButton jbPackingFullQuantityArrival;
    private javax.swing.JLabel jlDatetimeArrival;
    private javax.swing.JLabel jlDatetimeDeparture;
    private javax.swing.JLabel jlDriver;
    private javax.swing.JLabel jlDummy;
    private javax.swing.JLabel jlFreightOrigin;
    private javax.swing.JLabel jlInputSource;
    private javax.swing.JLabel jlItem;
    private javax.swing.JLabel jlNote;
    private javax.swing.JLabel jlOpeArr;
    private javax.swing.JLabel jlOpeDep;
    private javax.swing.JLabel jlPackingEmptyQuantityArrival;
    private javax.swing.JLabel jlPackingEmptyQuantityArrivalUnit;
    private javax.swing.JLabel jlPackingEmptyQuantityDeparture;
    private javax.swing.JLabel jlPackingEmptyQuantityDepartureUnit;
    private javax.swing.JLabel jlPackingFullQuantityArrival;
    private javax.swing.JLabel jlPackingFullQuantityArrivalUnit;
    private javax.swing.JLabel jlPackingFullQuantityDeparture;
    private javax.swing.JLabel jlPackingFullQuantityDepartureUnit;
    private javax.swing.JLabel jlPackingFullQuantityDepartureUnit1;
    private javax.swing.JLabel jlPackingFullQuantityDepartureUnit2;
    private javax.swing.JLabel jlPackingFullQuantityDepartureUnit3;
    private javax.swing.JLabel jlPackingFullQuantityDepartureUnit4;
    private javax.swing.JLabel jlPlates;
    private javax.swing.JLabel jlPlatesCage;
    private javax.swing.JLabel jlProducer;
    private javax.swing.JLabel jlRegion;
    private javax.swing.JLabel jlScale;
    private javax.swing.JLabel jlTicDest;
    private javax.swing.JLabel jlTicFreight;
    private javax.swing.JLabel jlTicOrig;
    private javax.swing.JLabel jlTicket;
    private javax.swing.JLabel jlWeightAverage;
    private javax.swing.JLabel jlWeightAverageUnit;
    private javax.swing.JLabel jlWeightDestinyArrival;
    private javax.swing.JLabel jlWeightDestinyArrivalUnit;
    private javax.swing.JLabel jlWeightDestinyDeparture;
    private javax.swing.JLabel jlWeightDestinyDepartureUnit;
    private javax.swing.JLabel jlWeightSource;
    private javax.swing.JLabel jlWeightSourceUnit;
    private sa.lib.gui.bean.SBeanFieldBoolean moBoolTared;
    private sa.lib.gui.bean.SBeanFieldBoolean moBoolWeightSourceAvailable;
    private sa.lib.gui.bean.SBeanFieldDatetime moDatetimeArrival;
    private sa.lib.gui.bean.SBeanFieldDatetime moDatetimeDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingEmptyQuantityArrival;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingEmptyQuantityDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingFullQuantityArrival;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecPackingFullQuantityDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightAverage;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightDestinyArrival;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightDestinyDeparture;
    private sa.lib.gui.bean.SBeanFieldDecimal moDecWeightSource;
    private sa.lib.gui.bean.SBeanFieldKey moKeyFreightOrigin;
    private sa.lib.gui.bean.SBeanFieldKey moKeyInputSource;
    private sa.lib.gui.bean.SBeanFieldKey moKeyItem;
    private sa.lib.gui.bean.SBeanFieldKey moKeyProducer;
    private sa.lib.gui.bean.SBeanFieldKey moKeyRegion;
    private sa.lib.gui.bean.SBeanFieldKey moKeyScale;
    private sa.lib.gui.bean.SBeanFieldKey moKeyTicDest;
    private sa.lib.gui.bean.SBeanFieldKey moKeyTicFreight;
    private sa.lib.gui.bean.SBeanFieldKey moKeyTicOrig;
    private sa.lib.gui.bean.SBeanFieldRadio moRadDependent;
    private sa.lib.gui.bean.SBeanFieldRadio moRadFreight;
    private sa.lib.gui.bean.SBeanFieldText moTextDriver;
    private sa.lib.gui.bean.SBeanFieldText moTextNote;
    private sa.lib.gui.bean.SBeanFieldText moTextOpeArr;
    private sa.lib.gui.bean.SBeanFieldText moTextOpeDep;
    private sa.lib.gui.bean.SBeanFieldText moTextPlates;
    private sa.lib.gui.bean.SBeanFieldText moTextPlatesCage;
    private sa.lib.gui.bean.SBeanFieldText moTextScale;
    private sa.lib.gui.bean.SBeanFieldText moTextTicket;
    // End of variables declaration//GEN-END:variables

    @SuppressWarnings("unchecked")
    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 1040, 650);
        
        jbSaveSend = new JButton("Guardar y enviar al estado siguiente");
        jbSaveSend.setPreferredSize(new Dimension(250, 23));
        jbSaveSend.addActionListener(this);

        moKeyScale.setKeySettings(miClient, SGuiUtils.getLabelName(jlScale.getText()), true);
        moTextTicket.setTextSettings(SGuiUtils.getLabelName(jlTicket), 10, 1);
        moKeyProducer.setKeySettings(miClient, SGuiUtils.getLabelName(jlProducer.getText()), true);
        moKeyItem.setKeySettings(miClient, SGuiUtils.getLabelName(jlItem.getText()), true);
        moKeyInputSource.setKeySettings(miClient, SGuiUtils.getLabelName(jlInputSource.getText()), true);
        moKeyRegion.setKeySettings(miClient, SGuiUtils.getLabelName(jlRegion.getText()), true);
        moTextPlates.setTextSettings(SGuiUtils.getLabelName(jlPlates.getText()), 25);
        moTextPlatesCage.setTextSettings(SGuiUtils.getLabelName(jlPlatesCage.getText()), 25, 0);
        moTextDriver.setTextSettings(SGuiUtils.getLabelName(jlDriver.getText()), 150);
        moBoolWeightSourceAvailable.setBooleanSettings(SGuiUtils.getLabelName(moBoolWeightSourceAvailable.getText()), false);
        moDecWeightSource.setDecimalSettings(SGuiUtils.getLabelName(jlWeightSource.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, true);
        moDecWeightDestinyArrival.setDecimalSettings(SGuiUtils.getLabelName(jlWeightDestinyArrival.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, true);
        moDecWeightDestinyDeparture.setDecimalSettings(SGuiUtils.getLabelName(jlWeightDestinyDeparture.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, true);
        moDecWeightAverage.setDecimalSettings(SGuiUtils.getLabelName(jlWeightAverage.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDatetimeArrival.setDateSettings(miClient, SGuiUtils.getLabelName(jlDatetimeArrival.getText()), true);
        moDatetimeDeparture.setDateSettings(miClient, SGuiUtils.getLabelName(jlDatetimeDeparture.getText()), true);
        moTextOpeArr.setTextSettings(SGuiUtils.getLabelName(jlOpeArr.getText()), 35, 0);
        moTextOpeDep.setTextSettings(SGuiUtils.getLabelName(jlOpeDep.getText()), 35, 0);
        moDecPackingFullQuantityArrival.setDecimalSettings(SGuiUtils.getLabelName(jlPackingFullQuantityArrival.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecPackingEmptyQuantityArrival.setDecimalSettings(SGuiUtils.getLabelName(jlPackingEmptyQuantityArrival.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecPackingFullQuantityDeparture.setDecimalSettings(SGuiUtils.getLabelName(jlPackingFullQuantityDeparture.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moDecPackingEmptyQuantityDeparture.setDecimalSettings(SGuiUtils.getLabelName(jlPackingEmptyQuantityDeparture.getText()), SGuiConsts.GUI_TYPE_DEC_QTY, false);
        moTextNote.setTextSettings(SGuiUtils.getLabelName(jlNote.getText()), 255, 0);
        moKeyTicOrig.setKeySettings(miClient, SGuiUtils.getLabelName(jlTicOrig.getText()), true);
        moKeyTicDest.setKeySettings(miClient, SGuiUtils.getLabelName(jlTicDest.getText()), true);
        moRadFreight.setBooleanSettings(moRadFreight.getText(), false);
        moRadDependent.setBooleanSettings(moRadDependent.getText(), false);
        moKeyFreightOrigin.setKeySettings(miClient, SGuiUtils.getLabelName(jlFreightOrigin), true);
        moKeyTicFreight.setKeySettings(miClient, SGuiUtils.getLabelName(jlTicFreight), true);

        moFields.addField(moKeyScale);
        moFields.addField(moTextTicket);
        moFields.addField(moKeyProducer);
        moFields.addField(moKeyItem);
        moFields.addField(moKeyInputSource);
        moFields.addField(moKeyRegion);
        moFields.addField(moTextPlates);
        moFields.addField(moTextPlatesCage);
        moFields.addField(moTextDriver);
        moFields.addField(moBoolWeightSourceAvailable);
        moFields.addField(moDecWeightSource);
        moFields.addField(moDecWeightDestinyArrival);
        moFields.addField(moDecWeightDestinyDeparture);
        moFields.addField(moDecWeightAverage);
        moFields.addField(moDatetimeArrival);
        moFields.addField(moDatetimeDeparture);
        moFields.addField(moTextOpeArr);
        moFields.addField(moTextOpeDep);
        moFields.addField(moDecPackingFullQuantityArrival);
        moFields.addField(moDecPackingEmptyQuantityArrival);
        moFields.addField(moDecPackingFullQuantityDeparture);
        moFields.addField(moDecPackingEmptyQuantityDeparture);
        moFields.addField(moTextNote);
        moFields.addField(moKeyTicOrig);
        moFields.addField(moKeyTicDest);
        moFields.addField(moRadFreight);
        moFields.addField(moRadDependent);
        moFields.addField(moKeyFreightOrigin);
        moFields.addField(moKeyTicFreight);
        
        moKeyTicFreight.removeAllItems();
        moKeyTicFreight.addItem(new SGuiItem("- Boleto del flete -"));

        moFields.setFormButton(jbSave);

        jpCommandCenter.add(jbSaveSend);
        
        jlWeightSourceUnit.setText(SSomConsts.KG);
        jlWeightDestinyArrivalUnit.setText(SSomConsts.KG);
        jlWeightDestinyDepartureUnit.setText(SSomConsts.KG);
        
        msComentArr = "";
        msComentDep = "";
    }

    private void handleWindowActivated() throws InstantiationException, IllegalAccessException {
        if (mbFirstTime) {
            mbFirstTime = false;
            
            moConnectionRevuelta = SSomUtils.openConnectionRevueltaJdbc(miClient.getSession());
            if (moConnectionRevuelta == null) {
                miClient.showMsgBoxWarning("No se pudo establecer comunicación con el sistema Revuelta.");
            }
            
            setEnabledFields(true);
        }
    }

    private void attendWindowClosed() {
        if (moConnectionRevuelta != null) {
            try {
                if (!moConnectionRevuelta.isClosed()) {
                    moConnectionRevuelta.close();
                }
            }
            catch (Exception e) {
                SLibUtils.showException(this, e);
            }
        }
    }

    private void setEnabledFields(final boolean enableFields) {
        if (!moRegistry.isAlternative()) {
            if (mnFormSubtype == SModConsts.SX_TIC_TARE_PEND) {
                moBoolTared.setEditable(false);
                moTextTicket.setEditable(false);
                jbImportTicket.setEnabled(false);
                jbCleanTicket.setEnabled(false);
                moKeyProducer.setEnabled(false);
                moKeyItem.setEnabled(false);
                moKeyInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
                jbInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
                moTextPlates.setEditable(false);
                moTextPlatesCage.setEditable(false);
                moTextDriver.setEditable(false);
                moTextOpeArr.setEnabled(false);
                moTextOpeDep.setEnabled(false);
                moDecWeightSource.setEditable(false);
                moBoolWeightSourceAvailable.setEnabled(false);
                moDecWeightDestinyArrival.setEditable(false);
                moDecWeightDestinyDeparture.setEditable(enableFields);
                moDatetimeArrival.setEditable(false);
                moDatetimeDeparture.setEditable(enableFields);
                moDecPackingFullQuantityArrival.setEditable(false);
                jbPackingFullQuantityArrival.setEnabled(mbIsPacking);
                moDecPackingEmptyQuantityArrival.setEditable(false);
                jbPackingEmptyQuantityArrival.setEnabled(mbIsPacking);
                moDecPackingFullQuantityDeparture.setEditable(mbIsPacking);
                moDecPackingEmptyQuantityDeparture.setEditable(mbIsPacking);
                jbImportTareTicket.setEnabled(enableFields && moConnectionRevuelta != null);
                jbCleanTare.setEnabled(!enableFields);
                jbSaveSend.setEnabled(enableFields && moRegistry != null && moRegistry.getFkTicketStatusId() == SModSysConsts.SS_TIC_ST_SCA);
                moKeyTicOrig.setEnabled(enableFields);
                moKeyTicDest.setEnabled(enableFields);
                if (moKeyRegion.getItemCount() <= 2) {
                    moKeyRegion.setEnabled(false);
                }
                else {
                    moKeyRegion.setEnabled(true);
                }
                moRadFreight.setEnabled(false);
                moRadDependent.setEnabled(false);
                moKeyFreightOrigin.setEnabled(false);
                moKeyTicFreight.setEnabled(false);
            }
            else {
                if (moRegistry.isRegistryNew()) {
                    moBoolTared.setEditable(false);
                    moTextTicket.setEditable(enableFields);
                    jbImportTicket.setEnabled(enableFields && moConnectionRevuelta != null);
                    jbCleanTicket.setEnabled(!enableFields);
                    moKeyProducer.setEnabled(enableFields);
                    moKeyItem.setEnabled(enableFields);
                    moKeyInputSource.setEnabled(enableFields && moKeyInputSource.getItemCount() > 1);
                    jbInputSource.setEnabled(enableFields && moKeyInputSource.getItemCount() > 1); 
                    moTextPlates.setEditable(enableFields);
                    moTextPlatesCage.setEditable(true);
                    moTextDriver.setEditable(enableFields);
                    moDecWeightSource.setEditable(moBoolWeightSourceAvailable.getValue());
                    moBoolWeightSourceAvailable.setEnabled(true);
                    moDecWeightDestinyArrival.setEditable(enableFields);
                    moDecWeightDestinyDeparture.setEditable(false);
                    moTextOpeArr.setEnabled(false);
                    moTextOpeDep.setEnabled(false);
                    moDatetimeArrival.setEditable(enableFields);
                    moDatetimeDeparture.setEditable(false);
                    moDecPackingFullQuantityArrival.setEditable(false);
                    jbPackingFullQuantityArrival.setEnabled(false);
                    moDecPackingEmptyQuantityArrival.setEditable(false);
                    jbPackingEmptyQuantityArrival.setEnabled(false);
                    moDecPackingFullQuantityDeparture.setEditable(false);
                    moDecPackingEmptyQuantityDeparture.setEditable(false);
                    jbImportTareTicket.setEnabled(false);
                    jbCleanTare.setEnabled(false);
                    jbSaveSend.setEnabled(true);
                    moKeyTicOrig.setEnabled(true);
                    moKeyTicDest.setEnabled(true);
                    if (moKeyRegion.getItemCount() <= 2) {
                        moKeyRegion.setEnabled(false);
                    }
                    else {
                        moKeyRegion.setEnabled(true);
                    }
                    moRadFreight.setEnabled(isFreightApply());
                    moRadDependent.setEnabled(isFreightApply());
                    actionRadEnableFreight();
                }
                else {
                    boolean enable = (!mbIsRevImport1 && !moRegistry.isTared());

                    moBoolTared.setEditable(false);
                    moTextTicket.setEditable(enable);
                    jbImportTicket.setEnabled(enable && moConnectionRevuelta != null);
                    jbCleanTicket.setEnabled(!enable && !moRegistry.isTared());
                    moKeyProducer.setEnabled(enable);
                    moKeyItem.setEnabled(enable);
                    moKeyInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
                    jbInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
                    moTextPlates.setEditable(enable);
                    moTextPlatesCage.setEditable(!moRegistry.isTared());
                    moTextDriver.setEditable(enable);
                    moDecWeightSource.setEditable(!moRegistry.isTared() && moBoolWeightSourceAvailable.getValue());
                    moBoolWeightSourceAvailable.setEnabled(!moRegistry.isTared());
                    moDecWeightDestinyArrival.setEditable(enable);
                    moDecWeightDestinyDeparture.setEditable(false);
                    moTextOpeArr.setEnabled(false);
                    moTextOpeDep.setEnabled(false);
                    moDatetimeArrival.setEditable(enable);
                    moDatetimeDeparture.setEditable(false);
                    moDecPackingFullQuantityArrival.setEditable(mbIsPacking && !moRegistry.isTared());
                    jbPackingFullQuantityArrival.setEnabled(false);
                    moDecPackingEmptyQuantityArrival.setEditable(mbIsPacking && !moRegistry.isTared());
                    jbPackingEmptyQuantityArrival.setEnabled(false);
                    moDecPackingFullQuantityDeparture.setEditable(false);
                    moDecPackingEmptyQuantityDeparture.setEditable(false);
                    jbImportTareTicket.setEnabled(false);
                    jbCleanTare.setEnabled(false);
                    jbSaveSend.setEnabled(true);
                    moKeyTicOrig.setEnabled(!enable);
                    moKeyTicDest.setEnabled(!enable);
                    if (enable) {
                        if (moKeyRegion.getItemCount() <= 2) {
                            moKeyRegion.setEnabled(false);
                        }
                        else {
                            moKeyRegion.setEnabled(true);
                        }
                    }
                    else {
                        moKeyRegion.setEnabled(false);                        
                    }
                    moRadFreight.setEnabled(isFreightApply());
                    moRadDependent.setEnabled(isFreightApply());
                    actionRadEnableFreight();
                }
            }
        }
        else {
            miClient.showMsgBoxInformation("No se puede modificar el boleto debido a que tiene un registro en el sistema de SOM Orgánico.\n"
                    + "Elimine el registro " + moRegistry.getXtaNumAlternative() + " en SOM Orgánico para modificar.\n"
                    + "Para enviar al estado siguiente hacerlo desde la vista de boletos");
            moBoolTared.setEditable(false);
            moTextTicket.setEditable(false);
            jbImportTicket.setEnabled(false);
            jbCleanTicket.setEnabled(false);
            moKeyProducer.setEnabled(false);
            moKeyItem.setEnabled(false);
            moKeyInputSource.setEnabled(false);
            jbInputSource.setEnabled(false);
            moTextPlates.setEditable(false);
            moTextPlatesCage.setEditable(false);
            moTextDriver.setEditable(false);
            moTextOpeArr.setEnabled(false);
            moTextOpeDep.setEnabled(false);
            moDecWeightSource.setEditable(false);
            moBoolWeightSourceAvailable.setEnabled(false);
            moDecWeightDestinyArrival.setEditable(false);
            moDecWeightDestinyDeparture.setEditable(false);
            moDatetimeArrival.setEditable(false);
            moDatetimeDeparture.setEditable(false);
            moDecPackingFullQuantityArrival.setEditable(false);
            jbPackingFullQuantityArrival.setEnabled(false);
            moDecPackingEmptyQuantityArrival.setEditable(false);
            jbPackingEmptyQuantityArrival.setEnabled(false);
            moDecPackingFullQuantityDeparture.setEditable(false);
            moDecPackingEmptyQuantityDeparture.setEditable(false);
            jbImportTareTicket.setEnabled(false);
            jbCleanTare.setEnabled(false);
            jbSaveSend.setEnabled(false);
            moKeyTicOrig.setEnabled(false);
            moKeyTicDest.setEnabled(false);
            jbSave.setEnabled(false);
            moTextNote.setEnabled(false);
            moKeyRegion.setEnabled(false);
            moRadFreight.setEnabled(false);
            moRadDependent.setEnabled(false);
            moKeyFreightOrigin.setEnabled(false);
            moKeyTicFreight.setEnabled(false);
        }
    }
    
    private boolean isFreightApply() {
        try {
            if (moItem != null) {
                switch (SSomUtils.getReqFreightByItem(miClient.getSession(), moItem.getPkItemId())) {
                    case SModSysConsts.SX_REQ_FRE_NO:
                        return false;
                    case SModSysConsts.SX_REQ_FRE_YES:
                        return true;
                }                
            }
        }
        catch (Exception e) {
            miClient.showMsgBoxError(e.getMessage());
        }
        return false;
    }

    private void itemStateKeyProducer() {
        if (moKeyProducer.getSelectedIndex() <= 0) {
            moProducer = null;
        }
        else {
            moProducer = (SDbProducer) miClient.getSession().readRegistry(SModConsts.SU_PROD, moKeyProducer.getValue());
            moKeyInputSource.setValue(new int[] { moProducer.getFkInputSourceId() });
            readRegion();
        }
    }

    private void itemStateKeyItem() {
        mbIsPacking = false;
        mbIsLaboratory = false;
        moDecPackingFullQuantityArrival.setValue(0d);
        moDecPackingEmptyQuantityArrival.setValue(0d);
        moDecPackingFullQuantityDeparture.setValue(0d);
        moDecPackingEmptyQuantityDeparture.setValue(0d);
        jlPackingFullQuantityArrivalUnit.setText("");
        jlPackingEmptyQuantityArrivalUnit.setText("");
        jlPackingFullQuantityDepartureUnit.setText("");
        jlPackingEmptyQuantityDepartureUnit.setText("");
        jlWeightAverageUnit.setText("");
        moDecPackingFullQuantityArrival.setEditable(mbIsPacking);
        moDecPackingEmptyQuantityArrival.setEditable(mbIsPacking);
        buttonGroup1.clearSelection();
        
        moKeyInputSource.removeAllItems();
        moKeyInputSource.setEnabled(false);

        if (moKeyItem.getSelectedIndex() > 0) {
            try {
                readItem();

                mbIsPacking = moItem.isPacking();
                mbIsLaboratory = moItem.isLaboratory();
                jlPackingFullQuantityArrivalUnit.setText(moItem.getPackingName());
                jlPackingEmptyQuantityArrivalUnit.setText(moItem.getPackingName());
                jlPackingFullQuantityDepartureUnit.setText(moItem.getPackingName());
                jlPackingEmptyQuantityDepartureUnit.setText(moItem.getPackingName());
                moDecPackingFullQuantityArrival.setEditable(mbIsPacking);
                moDecPackingEmptyQuantityArrival.setEditable(mbIsPacking);

                if (!jlWeightDestinyDepartureUnit.getText().isEmpty() && !moItem.getPackingName().isEmpty()) {
                    jlWeightAverageUnit.setText(jlWeightDestinyDepartureUnit.getText() + "/" + moItem.getPackingName());
                }
                else {
                    jlWeightAverageUnit.setText("");
                }
                
                miClient.getSession().populateCatalogue(moKeyInputSource, SModConsts.SU_INP_SRC, SLibConsts.UNDEFINED, new SGuiParams(moItem.getFkInputCategoryId()));
                moKeyInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
                jbInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
                if (moProducer != null) {
                    moKeyInputSource.setValue(new int[] { moProducer.getFkInputSourceId() });
                }
                
                readRegion();
                reloadFreightTicketsCatalog();
            }
            catch (SQLException e) {
                SLibUtils.showException(this, e);
            }
            catch (Exception e) {
                SLibUtils.showException(this, e);
            }
        }
    }
    
    private void readItem() throws SQLException, Exception {
        if (moKeyItem.getSelectedIndex() <= 0) {
            moItem = null;
        }
        else {
            moItem = (SDbItem) miClient.getSession().readRegistry(SModConsts.SU_ITEM, moKeyItem.getValue());
        }
    }
    
    private void reloadFreightTicketsCatalog() {
        SGuiParams params = new SGuiParams();
        params.getParamsMap().put(SModConsts.SU_INP_CT, moItem != null ? moItem.getFkInputCategoryId() : 0);
        params.getParamsMap().put(SModConsts.SX_TIC_DATE, moRegistry.getDate() != null ? moRegistry.getDate() : miClient.getSession().getWorkingDate());
        miClient.getSession().populateCatalogue(moKeyTicFreight, SModConsts.SX_TIC_FREIGHT, SLibConsts.UNDEFINED, params);
    }

    private void itemStateWeightSourceAvailable() {
        moDecWeightSource.setEditable(moBoolWeightSourceAvailable.getValue());
    }

    private void computeWeightAverage() {
        if (moDecWeightDestinyDeparture.getValue() > 0 && (moDecPackingFullQuantityArrival.getValue() > 0 || moDecPackingFullQuantityDeparture.getValue() > 0)) {
            // tare - packing_net_weight / full_packing_net_quantity:
            moDecWeightAverage.setValue(((moDecWeightDestinyArrival.getValue() - moDecWeightDestinyDeparture.getValue()) -
                ((moDecPackingFullQuantityArrival.getValue() + moDecPackingEmptyQuantityArrival.getValue()) * moItem.getPackingWeight()) +
                ((moDecPackingFullQuantityDeparture.getValue() + moDecPackingEmptyQuantityDeparture.getValue()) * moItem.getPackingWeight())) /
                (moDecPackingFullQuantityArrival.getValue() - moDecPackingFullQuantityDeparture.getValue()));
        }
    }

    private void actionImportTicket() {
        int producerId = 0;
        int itemId = 0;
        String sql = "";
        String producerRevId  = "";
        String itemRevId = "";
        Statement statement = null;
        ResultSet resulset = null;
        //SimpleDateFormat datetimeParser = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss a"); // deprecated code (Sergio Flores, 2019-06-10)
        //SimpleDateFormat dateFormatDateShort = new SimpleDateFormat("MM/dd/yyyy"); // XXX used when ODBC was supported by JVM (Sergio Flores, 2015-06-24)

        if (moConnectionRevuelta != null) {
            try {
                if (moKeyScale.getSelectedIndex() > 0) {
                    if (!SSomUtils.existsTicket(miClient.getSession(), moTextTicket.getValue(), moRegistry.getPkTicketId())) {
                        statement = moConnectionRevuelta.createStatement();

                        /* XXX used when ODBC was supported by JVM (Sergio Flores 2015-06-24)
                        sql = "SELECT be.clave_e, DateValue(be.fecha_e) + TimeValue(be.hora_e), be.placas, be.observa_e, be.conductor, be.peso_e, " + // 6
                                "be.clave_p, be.clave_c, be.clave_o, be.nombre_oe, be.turno_oe, be.bascula_e, p.nombre_p, c.nombre_c " + // 14
                                "FROM ((boleto_ent AS be " +
                                "INNER JOIN producto AS p ON be.clave_p = p.clave_p) " +
                                "INNER JOIN cliente AS c ON be.clave_c = c.clave_c) " +
                                "WHERE be.clave_e = " + moIntTicket.getValue() + " AND be.fecha_e = #" + dateFormatDateShort.format(moDatetimeArrival.getValue()) + "# ";
                        */
                        /* Deprecation due to change of DBMS of Revuelta's scale software (Alfredo Pérez, 2018-02-19)
                        sql = "SELECT 
                                be.clave_e,
                                CAST(DATE(be.fecha_e) AS SQL_CHAR) + ' ' + be.hora_e, 
                                be.placas, 
                                be.observa_e,
                                be.conductor, 
                                be.peso_e, " +  // 6
                                "be.clave_p,
                                be.clave_c,     //8
                                be.clave_o,     
                                be.nombre_oe,   //10 
                                be.turno_oe, 
                                be.bascula_e,   //12
                                p.nombre_p,
                                c.nombre_c " + // 14
                                "FROM ((boleto_ent AS be " +
                                "INNER JOIN producto AS p ON be.clave_p = p.clave_p) " +
                                "INNER JOIN cliente AS c ON be.clave_c = c.clave_c) " +
                                "WHERE be.clave_e = " + moIntTicket.getValue() + " AND be.fecha_e = '" + SLibUtils.DbmsDateFormatDate.format(moDatetimeArrival.getValue()) + "' ";
                        
                        */
                        sql = "SELECT Pes_ID, Pro_ID, Emp_ID, Pes_Placas, Pes_Chofer, Pes_FecHorPri, Usb_Nombre, Emp_Nombre, Pro_Nombre, "
                                + "Pes_BasPri, Pes_OpeNomPri, Pes_ObsPri, Pes_PesoPri, Pes_FecHorSeg, Pes_BasSeg, Pes_Bruto, Pes_Tara, Pes_Neto, Pes_OpeNomSeg, Pes_ObsSeg "
                                + "FROM dba.Pesadas "
                                + "WHERE Pes_ID = " + moTextTicket.getValue();

                        resulset = statement.executeQuery(sql);
                        if (resulset.next()) {
                            producerRevId = resulset.getString("Emp_ID");
                            itemRevId = resulset.getString("Pro_ID");

                            producerId = SSomUtils.mapProducerSomRevuelta(miClient.getSession(), producerRevId);
                            itemId = SSomUtils.mapItemSomRevuelta(miClient.getSession(), itemRevId);

                            if (producerId > 0) {
                                if (itemId > 0) {
                                    /* Deprecation due to change of DBMS of Revuelta's scale software (Alfredo Pérez, 2018-02-19)
                                    moTextPlates.setValue(resulset.getString(3));
                                    moTextDriver.setValue(resulset.getString(5));
                                    moDecWeightDestinyArrival.setValue(resulset.getDouble(6));
                                    moDatetimeArrival.setValue(SLibUtils.DbmsDateFormatDatetime.parse(resulset.getString(2)));
                                    moDatetimeArrival.setValue(datetimeParser.parse(resulset.getString(2).replaceAll("a.m.", "AM").replaceAll("p.m.", "PM")));
                                    moTextNote.setValue(resulset.getString(4));
                                    */
                                    moKeyProducer.setValue(new int [] { producerId });
                                    moKeyItem.setValue(new int [] { itemId });
                                    moTextPlates.setValue(resulset.getString("Pes_Placas"));
                                    moTextDriver.setValue(resulset.getString("Pes_Chofer"));
                                    moDecWeightDestinyArrival.setValue(resulset.getDouble("Pes_PesoPri"));
                                    moDatetimeArrival.setValue((resulset.getTimestamp("Pes_FecHorPri")));
                                    moTextOpeArr.setValue(resulset.getString("Pes_OpeNomPri"));
                                    moTextNote.setValue(resulset.getString("Pes_ObsPri"));
                                    msComentArr = resulset.getString("Pes_ObsPri");
                                    moKeyScale.setEnabled(false);
                                    mbIsRevImport1 = true;

                                    setEnabledFields(false);
                                    itemStateKeyItem();
                                }
                                else {
                                    miClient.showMsgBoxInformation("No se encontró el mapeo para el producto '" + resulset.getString("Pro_Nombre") + "', en el catálogo de ítems de SOM.");
                                }
                            }
                            else {
                                miClient.showMsgBoxInformation("No se encontró el mapeo para el proveedor '" + resulset.getString("Emp_Nombre") + "', en el catálogo de proveedores de SOM.");
                            }
                        }
                        else {
                            miClient.showMsgBoxInformation("No se encontró ningún registro para el boleto '" + moTextTicket.getValue() + "', del día '" + SLibUtils.DateFormatDate.format(moDatetimeArrival.getValue()) + "', en Revuelta.");
                        }
                    }
                    else {
                        miClient.showMsgBoxInformation("El boleto '" + moTextTicket.getValue() + "', ya existe.");
                    }
                }
                else {
                    miClient.showMsgBoxInformation("Se debe especificar un valor para el campo '" + SGuiUtils.getLabelName(jlScale) + "'.");
                    moKeyScale.requestFocus();
                }
            }
            catch (ParseException | SQLException e) {
                SLibUtils.showException(this, e);
            }
            catch (Exception e) {
                SLibUtils.showException(this, e);
            }
        }
        else {
            miClient.showMsgBoxWarning("No se pudo establecer comunicación con el sistema Revuelta.");
        }
    }

    private void actionImportTareTicket() {
        String sql = "";
        Statement statement = null;
        ResultSet resulset = null;
        SimpleDateFormat datetimeParser = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss a");
        //SimpleDateFormat DateFormatDateShort = new SimpleDateFormat("MM/dd/yyyy");    // XXX used when ODBC was supported by JVM (Sergio Flores 2015-06-24)

        if (moConnectionRevuelta != null) {
            try {
                statement = moConnectionRevuelta.createStatement();

                /* XXX used when ODBC was supported by JVM (Sergio Flores 2015-06-24)
                sql = "SELECT clave_e, DateValue(fecha_s) + TimeValue(hora_s), peso_s " + // 3
                        "FROM boleto_sal " +
                        "WHERE clave_e = " + moIntTicket.getValue() + " AND fecha_s = #" + DateFormatDateShort.format(moDatetimeDeparture.getValue()) + "# ";
                */
                /* Deprecation due to change of DBMS of Revuelta's scale software (Alfredo Pérez, 2018-02-19)
                sql = "SELECT clave_e, CAST(DATE(fecha_s) AS SQL_CHAR) + ' ' + hora_s, peso_s " + // 3
                        "FROM boleto_sal " +
                        "WHERE clave_e = " + moIntTicket.getValue() + " AND fecha_s = '" + SLibUtils.DbmsDateFormatDate.format(moDatetimeDeparture.getValue()) + "' ";
                */
                        
                sql = "SELECT Pes_ID, Pro_ID, Emp_ID, Pes_FecHorSeg, Pes_BasSeg, Pes_Bruto, Pes_Tara, Pes_Neto,Pes_PesoSeg, Pes_OpeNomSeg, Pes_ObsSeg "
                        + "FROM dba.Pesadas "
                        + "WHERE Pes_ID = " + moTextTicket.getValue();
                resulset = statement.executeQuery(sql);
                if (resulset.next()) {
                    /* Deprecation due to change of DBMS of Revuelta's scale software (Alfredo Pérez, 2018-02-19)
                    moDecWeightDestinyDeparture.setValue(resulset.getDouble(3));
                    moDatetimeDeparture.setValue(SLibUtils.DbmsDateFormatDatetime.parse(resulset.getString(2)));
                    moDatetimeDeparture.setValue(datetimeParser.parse(resulset.getString(2).replaceAll("a.m.", "AM").replaceAll("p.m.", "PM")));
                    */
                    moDecWeightDestinyDeparture.setValue(resulset.getDouble("Pes_PesoSeg"));
                    moDatetimeDeparture.setValue(resulset.getTimestamp("Pes_FecHorSeg"));
                    moTextOpeDep.setValue(resulset.getString("Pes_OpeNomSeg"));
                    msComentDep = resulset.getString("Pes_ObsSeg");
                    mbIsRevImport2 = true;

                    setEnabledFields(false);
                }
                else {
                    miClient.showMsgBoxInformation("No se encontró ningún registro para el boleto '" + moTextTicket.getValue() + "', del día '" + SLibUtils.DateFormatDate.format(moDatetimeDeparture.getValue()) + ".");
                }
            }
            catch (SQLException e) {
                SLibUtils.showException(this, e);
            }
        }
        else {
            miClient.showMsgBoxWarning("No se pudo establecer comunicación con el sistema Revuelta.");
        }
    }

//    private void getSeasonRegion() {
//        mnSeasonId = 0;
//        mnRegionId = 0;
//
//        try {
//            mnSeasonId = SSomUtils.getProperSeasonId(miClient.getSession(), moDatetimeArrival.getValue(), moKeyItem.getValue()[0], moKeyProducer.getValue()[0]);
//
//            if (mnSeasonId != SLibConsts.UNDEFINED) {
//                mnRegionId = SSomUtils.getProperRegionId(miClient.getSession(), mnSeasonId, moKeyItem.getValue()[0], moKeyProducer.getValue()[0]);
//            }
//        }
//        catch (Exception e) {
//             SLibUtils.showException(this, e);
//        }
//    }
    
    private void readRegion() {
        mnSeasonId = 0;
        mnRegionId = 0;

        try {
            if (moKeyItem.getValue().length != 0) {
                mnSeasonId = SSomUtils.getProperSeasonId(miClient.getSession(), moDatetimeArrival.getValue(), moKeyItem.getValue()[0], moKeyProducer.getValue()[0]);

                SGuiParams params = new SGuiParams();
                params.getParamsMap().put(SModConsts.SU_SEAS, mnSeasonId);
                params.getParamsMap().put(SModConsts.SU_ITEM, moKeyItem.getValue()[0]);
                params.getParamsMap().put(SModConsts.SU_PROD, moKeyProducer.getValue()[0]);
                miClient.getSession().populateCatalogue(moKeyRegion, SModConsts.SX_PROD_REG_ITEM_SEAS, SLibConsts.UNDEFINED, params);
                
                setEnabledFields(moKeyItem.isEnabled());
                
                if (moKeyRegion.getItemCount() == 2) {
                    moKeyRegion.setEnabled(false);
                    moKeyRegion.setSelectedIndex(1);
                }
            }
        }
        catch (Exception e) {
             SLibUtils.showException(this, e);
        }
    }

    private void actionCleanTicket() {
        if (miClient.showMsgBoxConfirm("¿Está seguro(a) que desea borrar los datos de la primer pesada?") == JOptionPane.YES_OPTION) {
            moTextTicket.setValue("");
            moKeyProducer.setSelectedIndex(0);
            moKeyItem.setSelectedIndex(0);
            moTextPlates.setValue("");
            moTextPlatesCage.setValue("");
            moTextDriver.setValue("");
            moDecWeightDestinyArrival.setValue(0d);
            moDecWeightSource.setValue(0d);
            moDatetimeArrival.setValue(miClient.getSession().getWorkingDate());
            moTextOpeArr.setValue("");
            moTextNote.setValue("");
            msComentArr = "";
            mbIsRevImport1 = false;

            setEnabledFields(true);
        }
    }

    private void actionCleanTare() {
        if (miClient.showMsgBoxConfirm("¿Está seguro(a) que desea borrar los datos de la segunda pesada?") == JOptionPane.YES_OPTION) {
            moDecWeightDestinyDeparture.setValue(0d);
            moDatetimeDeparture.setValue(miClient.getSession().getWorkingDate());
            moTextOpeDep.setValue("");
            msComentDep = "";
            mbIsRevImport2 = false;

            setEnabledFields(true);
        }
    }
    
    private void actionInputSource() {
        if (jbInputSource.isEnabled()) {
            try {
                moKeyInputSource.setValue(new int[] { moProducer.getFkInputSourceId() });
            }
            catch (Exception e){
                miClient.showMsgBoxError("No hay origenes disponibles.");
            }
        }
    }

    private void actionSaveSend() {
        mbIsSaveSend = true;
        super.actionSave();
    }

    private void actionPackingFullQuantityArrival() {
        jbPackingFullQuantityArrival.setEnabled(false);
        moDecPackingFullQuantityArrival.setEditable(true);
        moDecPackingFullQuantityArrival.requestFocus();
    }

    private void actionPackingEmptyQuantityArrival() {
        jbPackingEmptyQuantityArrival.setEnabled(false);
        moDecPackingEmptyQuantityArrival.setEditable(true);
        moDecPackingEmptyQuantityArrival.requestFocus();
    }
    
    private void actionRadEnableFreight() {
        moKeyFreightOrigin.setEnabled(moRadFreight.isEnabled() && moRadFreight.isSelected());
        moKeyTicFreight.setEnabled(moRadDependent.isEnabled() && moRadDependent.isSelected());
        if (!moKeyFreightOrigin.isEnabled()) {
            moKeyFreightOrigin.setSelectedIndex(0);
        }
        if (!moKeyTicFreight.isEnabled() && moKeyTicFreight.getComponent().getItemCount() > 0) {
            moKeyTicFreight.setSelectedIndex(0);
        }
    }

    @Override
    public void addAllListeners() {
        moKeyProducer.addItemListener(this);
        moKeyItem.addItemListener(this);
        jbImportTicket.addActionListener(this);
        jbCleanTicket.addActionListener(this);
        jbInputSource.addActionListener(this);
        jbImportTareTicket.addActionListener(this);
        jbCleanTare.addActionListener(this);
        jbSaveSend.addActionListener(this);
        jbPackingFullQuantityArrival.addActionListener(this);
        moRadFreight.addActionListener(this);
        moRadDependent.addActionListener(this);
        moBoolWeightSourceAvailable.addItemListener(this);
        moDecWeightSource.addFocusListener(this);
        moDecWeightDestinyArrival.addFocusListener(this);
        moDecWeightDestinyDeparture.addFocusListener(this);
        moDecPackingFullQuantityArrival.addFocusListener(this);
        moDecPackingEmptyQuantityArrival.addFocusListener(this);
        moDecPackingFullQuantityDeparture.addFocusListener(this);
        moDecPackingEmptyQuantityDeparture.addFocusListener(this);
        moDatetimeArrival.getComponent().addChangeListener(this);
    }

    @Override
    public void removeAllListeners() {
        moKeyProducer.removeItemListener(this);
        moKeyItem.removeItemListener(this);
        jbImportTicket.removeActionListener(this);
        jbCleanTicket.removeActionListener(this);
        jbInputSource.removeActionListener(this);
        jbImportTareTicket.removeActionListener(this);
        jbCleanTare.removeActionListener(this);
        jbSaveSend.removeActionListener(this);
        jbPackingFullQuantityArrival.removeActionListener(this);
        moRadFreight.removeActionListener(this);
        moRadDependent.removeActionListener(this);
        moBoolWeightSourceAvailable.removeItemListener(this);
        moDecWeightSource.removeFocusListener(this);
        moDecWeightDestinyArrival.removeFocusListener(this);
        moDecWeightDestinyDeparture.removeFocusListener(this);
        moDecPackingFullQuantityArrival.removeFocusListener(this);
        moDecPackingEmptyQuantityArrival.removeFocusListener(this);
        moDecPackingFullQuantityDeparture.removeFocusListener(this);
        moDecPackingEmptyQuantityDeparture.removeFocusListener(this);
        moDatetimeArrival.getComponent().removeChangeListener(this);
    }

    @Override
    public void reloadCatalogues() {
        miClient.getSession().populateCatalogue(moKeyScale, SModConsts.CU_USR_SCA, SLibConsts.UNDEFINED, new SGuiParams(new int[] { miClient.getSession().getUser().getPkUserId() }));
        miClient.getSession().populateCatalogue(moKeyItem, SModConsts.SU_ITEM, SLibConsts.UNDEFINED, null);
        miClient.getSession().populateCatalogue(moKeyProducer, SModConsts.SU_PROD, SLibConsts.UNDEFINED, null);
        miClient.getSession().populateCatalogue(moKeyTicOrig, SModConsts.SU_TIC_ORIG, SLibConsts.UNDEFINED, null);
        miClient.getSession().populateCatalogue(moKeyTicDest, SModConsts.SU_TIC_DEST, SLibConsts.UNDEFINED, null);
        miClient.getSession().populateCatalogue(moKeyFreightOrigin, SModConsts.SU_FREIGHT_ORIG, SLibConsts.UNDEFINED, null);
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbTicket) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;
        mbFirstTime = true;
        mbIsSaveSend = false;

        removeAllListeners();
        reloadCatalogues();
        
        if (moRegistry.isRegistryNew()) {
            moRegistry.initPrimaryKey();
            moRegistry.setDatetimeArrival(miClient.getSession().getWorkingDate());
            moRegistry.setDatetimeDeparture(miClient.getSession().getWorkingDate());
            moKeyScale.setVisible(true);
            moTextScale.setVisible(false);
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moKeyScale.setValue(new int[] { moRegistry.getFkScaleId() });
        moBoolTared.setValue(moRegistry.isTared());
        moTextTicket.setValue(moRegistry.getNumber());
        moKeyProducer.setValue(new int[] { moRegistry.getFkProducerId() });
        itemStateKeyProducer();
        moKeyItem.setValue(new int[] { moRegistry.getFkItemId() });
        itemStateKeyItem();
        moKeyTicOrig.setValue(new int[] { moRegistry.getFkTicketOriginId() });
        moKeyTicDest.setValue(new int[] { moRegistry.getFkTicketDestinationId() });
        
        if (moRegistry.getFkInputSourceId() == SModSysConsts.SU_INP_SRC_NA) {
            moKeyInputSource.resetField();
        }
        else {
            moKeyInputSource.setValue(new int[] { moRegistry.getFkInputSourceId() });
        }
        
        moTextPlates.setValue(moRegistry.getPlate());
        moTextPlatesCage.setValue(moRegistry.getPlateCage());
        moTextDriver.setValue(moRegistry.getDriver());
        moDecWeightSource.setValue(moRegistry.getWeightSource());
        moBoolWeightSourceAvailable.setValue(moRegistry.isWeightSourceAvailable());
        moDecWeightDestinyArrival.setValue(moRegistry.getWeightDestinyArrival());
        moDecWeightDestinyDeparture.setValue(moRegistry.getWeightDestinyDeparture());
        moDatetimeArrival.setValue(moRegistry.getDatetimeArrival());
        moDatetimeDeparture.setValue(moRegistry.getDatetimeDeparture());
        moTextOpeArr.setValue(moRegistry.getScaleOperatorArrival());
        moTextOpeDep.setValue(moRegistry.getScaleOperatorDeparture());
        moDecPackingFullQuantityArrival.setValue(moRegistry.getPackingFullQuantityArrival());
        moDecPackingEmptyQuantityArrival.setValue(moRegistry.getPackingEmptyQuantityArrival());
        moDecPackingFullQuantityDeparture.setValue(moRegistry.getPackingFullQuantityDeparture());
        moDecPackingEmptyQuantityDeparture.setValue(moRegistry.getPackingEmptyQuantityDeparture());
        moTextNote.setValue("");
        msComentArr = moRegistry.getScaleCommentsArrival();
        msComentDep = moRegistry.getScaleCommentsDeparture();

        moTextScale.setValue(moRegistry.getXtaScaleName());
        mbIsRevImport1 = moRegistry.isRevueltaImport1();
        mbIsRevImport2 = moRegistry.isRevueltaImport2();

        if (moRegistry.getChildTicketNotes().size() > 0) {
            moTextNote.setValue(moRegistry.getChildTicketNotes().get(0).getNote());
        }

        setFormEditable(true);

        if (moRegistry.isRegistryNew()) {
            if (moKeyScale.getItemCount() == 2) {
                moKeyScale.setSelectedIndex(1);
                moKeyScale.setEnabled(false);
            }
            moBoolWeightSourceAvailable.setValue(true);

            moTextScale.setVisible(false);
            moTextScale.setEditable(false);
        }
        else {
            moKeyScale.setVisible(false);
            moKeyScale.setEnabled(false);
            moTextScale.setVisible(true);
            moTextScale.setEditable(false);
        }

        moKeyInputSource.setEnabled(moKeyInputSource.getItemCount() > 1);
        moDecWeightAverage.setEditable(false);
        
        buttonGroup1.clearSelection();
        moRadFreight.setSelected(moRegistry.getFkFreightOriginId_n() != 0);
        moRadDependent.setSelected(moRegistry.getFkFreightTicketId_n() != 0);
        moKeyFreightOrigin.setValue(new int[] { moRegistry.getFkFreightOriginId_n() });
        moKeyTicFreight.setValue(new int[] { moRegistry.getFkFreightTicketId_n() });
        
        itemStateWeightSourceAvailable();
        computeWeightAverage();
        readRegion();
        moKeyRegion.setValue(new int[] { moRegistry.getFkRegionId_n()} );

        addAllListeners();
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        SDbTicketNote ticketNote = new SDbTicketNote();
        SDbTicket registry = moRegistry.clone();

        if (registry.isRegistryNew()) {
            // nothing to do by now
        }

        //getSeasonRegion();
        //readRegion();

        registry.setNumber(moTextTicket.getValue());
        registry.setDate(moDatetimeArrival.getValue());
        //registry.setQuantity(...); // seemingly unused
        registry.setPlate(moTextPlates.getValue());
        registry.setPlateCage(moTextPlatesCage.getValue());
        registry.setDriver(moTextDriver.getValue());
        registry.setDatetimeArrival(moDatetimeArrival.getValue());
        registry.setDatetimeDeparture(moRegistry.isRegistryNew() ? moDatetimeArrival.getValue() : moDatetimeDeparture.getValue());
        
        registry.setPackingFullQuantityArrival(moDecPackingFullQuantityArrival.getValue());
        registry.setPackingEmptyQuantityArrival(moDecPackingEmptyQuantityArrival.getValue());
        
        registry.setWeightSource(moDecWeightSource.getValue());
        registry.setWeightDestinyArrival(moDecWeightDestinyArrival.getValue());
        registry.setScaleOperatorArrival(moTextOpeArr.getValue());
        registry.setScaleOperatorDeparture(moTextOpeDep.getValue());
        registry.setScaleCommentsArrival(msComentArr == null ? "" : msComentArr);
        registry.setScaleCommentsDeparture(msComentDep == null ? "" : msComentDep);
        
        boolean tared = mnFormSubtype == SModConsts.SX_TIC_TARE_PEND || moRegistry.isTared();
        
        if (tared) {
            registry.setPackingFullQuantityDeparture(moDecPackingFullQuantityDeparture.getValue());
            registry.setPackingEmptyQuantityDeparture(moDecPackingEmptyQuantityDeparture.getValue());
            
            registry.setWeightDestinyDeparture(moDecWeightDestinyDeparture.getValue());
        }
        else {
            registry.setPackingFullQuantityDeparture(0);
            registry.setPackingEmptyQuantityDeparture(0);
            
            registry.setWeightDestinyDeparture(0);
        }
        
        //registry.setWeightDestinyGross_r(...);
        //registry.setWeightDestinyNet_r(...);
        //registry.setSystemPenaltyPercentage(...);
        //registry.setSystemWeightPayment(...);
        //registry.setSystemPricePerTon(...);
        //registry.setSystemPayment_r(...);
        //registry.setSystemFreight(...);
        //registry.setSystemTotal_r(...);
        //registry.setUserPenaltyPercentage(...);
        //registry.setUserWeightPayment(...);
        //registry.setUserPricePerTon(...);
        //registry.setUserPayment_r(...);
        //registry.setUserFreight(...);
        //registry.setUserTotal_r(...);
        //registry.setDpsSupplyDate_n(...);
        registry.setRevueltaImport1(mbIsRevImport1);
        registry.setRevueltaImport2(mbIsRevImport2);
        registry.setWeightSourceAvailable(moBoolWeightSourceAvailable.getValue());
        registry.setMfgOutsourcing(false);
        registry.setTared(tared);
        registry.setPayed(false);
        registry.setAssorted(false);
        registry.setPacking(mbIsPacking);
        registry.setLaboratory(mbIsLaboratory);
        registry.setDpsSupply(false);
        //registry.setDeleted(...);
        //registry.setSystem(...);
        registry.setFkScaleId(moKeyScale.isVisible() ? moKeyScale.getValue()[0] : registry.getFkScaleId());
        registry.setFkTicketStatusId(registry.isRegistryNew() ? SModSysConsts.SS_TIC_ST_SCA : registry.getFkTicketStatusId());
        registry.setFkSeasonId_n(mnSeasonId);
        registry.setFkRegionId_n(moKeyRegion.getValue().length == 0 ? 0 : moKeyRegion.getValue()[0]);
        registry.setFkItemId(moKeyItem.getValue()[0]);
        registry.setFkUnitId(moKeyItem.getSelectedItem().getForeignKey()[0]);
        registry.setFkProducerId(moKeyProducer.getValue()[0]);
        registry.setFkInputSourceId(!moKeyInputSource.isEnabled() ? SModSysConsts.SU_INP_SRC_NA : moKeyInputSource.getValue()[0]);
        registry.setFkLaboratoryId_n(registry.isRegistryNew() ? 0 : registry.getFkLaboratoryId_n());
        registry.setFkTicketOriginId(moKeyTicOrig.getValue()[0]);
        registry.setFkTicketDestinationId(moKeyTicDest.getValue()[0]);
        //registry.setFkExternalDpsYearId_n(...);
        //registry.setFkExternalDpsDocId_n(...);
        //registry.setFkExternalDpsEntryId_n(...);
        //registry.setFkUserTaredId(miClient.getSession().getUser().getPkUserId());
        //registry.setFkUserPayedId(...);
        //registry.setFkUserAssortedId(...);
        
        registry.setAuxRequirePriceComputation(!mbIsLaboratory && mnFormSubtype == SModConsts.SX_TIC_TARE_PEND);

        if (mnFormSubtype == SModConsts.SX_TIC_TARE_PEND) {
            if (moItem.isAutoMailNotification()) {
                registry.setAuxSendMailOnSaveForItems(true);
                registry.setAuxMailRecipientsForItems(moItem.getAutoMailNotificationBoxes());
            }
            
            if (moProducer.isAutoMailNotification()) {
                registry.setAuxSendMailOnSaveForProducer(true);
                registry.setAuxMailRecipientsForProducer(moProducer.getAutoMailNotificationBoxes());
            }
        }

        registry.setAuxMoveNextOnSend(mbIsSaveSend);

        registry.getChildTicketNotes().clear();
        if (!moTextNote.getValue().isEmpty()) {
            ticketNote.setNote(moTextNote.getValue());
            registry.getChildTicketNotes().add(ticketNote);
        }
        
        if (isFreightApply()) {
            registry.setRequiredFreight(SModSysConsts.SX_REQ_FRE_YES);
            if (moRadFreight.isSelected()) {
                registry.setFreightTicketType(SModSysConsts.SX_FREIGHT_TIC_TP_FRE);
                registry.setFkFreightOriginId_n(moKeyFreightOrigin.getValue()[0]);
            }
            else {
                registry.setFreightTicketType(SModSysConsts.SX_FREIGHT_TIC_TP_DEP);
                registry.setFkFreightTicketId_n(moKeyTicFreight.getValue()[0]);
            }
        }
        else {
            registry.setRequiredFreight(SModSysConsts.SX_REQ_FRE_NO);
        }
        
        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();
        
        if (validation.isValid()) {
            if (!SGuiClientUtils.isPeriodOpened(miClient.getSession(), moDatetimeArrival.getValue())) {
                validation.setMessage("El período está cerrado.");
                validation.setComponent(((JSpinner.DefaultEditor) moDatetimeArrival.getComponent().getEditor()).getTextField());
            }
            else {
                if (mnFormSubtype == SModConsts.SX_TIC_TARE_PEND) {
                    if (moKeyInputSource.getItemCount() > 1 && moKeyInputSource.getSelectedIndex() <= 0) {
                        validation.setMessage(SGuiConsts.ERR_MSG_FIELD_REQ + "'" + moKeyInputSource.getFieldName() + "'." +
                                (moKeyInputSource.isEnabled() ? "" : "Favor de modificar este registro desde la vista 'Boletos báscula'."));
                        if (moKeyInputSource.isEnabled()) {
                            validation.setComponent(moKeyInputSource);
                        }
                    }
                    
                    if (validation.isValid() && !mbIsRevImport2) {
                        validation = SGuiUtils.validateDateRange(moDatetimeArrival, moDatetimeDeparture);
                        if (!validation.isValid()) {
                            if (moDatetimeArrival.isEditable()) {
                                validation.setComponent(((JSpinner.DefaultEditor) moDatetimeArrival.getComponent().getEditor()).getTextField());
                            }
                            else if (moDatetimeDeparture.isEditable()) {
                                validation.setComponent(((JSpinner.DefaultEditor) moDatetimeDeparture.getComponent().getEditor()).getTextField());
                            }
                        }
                    }  
                }
                
                if (validation.isValid()) {
                    if (moKeyTicOrig.getSelectedIndex() <= 0 || moKeyTicOrig.getValue()[0] == SModSysConsts.SU_TIC_ORIG_NA) {
                        validation.setMessage("Debe seleccionar la procedencia del boleto.");
                        validation.setComponent(moKeyTicOrig);
                    }
                } 

                if (validation.isValid()) {
                    if (moKeyTicDest.getSelectedIndex() <= 0 || moKeyTicDest.getValue()[0] == SModSysConsts.SU_TIC_DEST_NA) {
                        validation.setMessage("Debe seleccionar el destino del boleto.");
                        validation.setComponent(moKeyTicDest);
                    }
                } 

                if (validation.isValid()) {
                    if (moDecPackingFullQuantityArrival.isEditable() && moDecPackingFullQuantityArrival.getValue() == 0) {
                        if (miClient.showMsgBoxConfirm("No tiene valor el campo '" + SGuiUtils.getLabelName(jlPackingFullQuantityArrival.getText()) + "',\n" + SGuiConsts.MSG_CNF_CONT) != JOptionPane.YES_OPTION) {
                            validation.setMessage(SGuiConsts.ERR_MSG_FIELD_REQ + "'" + SGuiUtils.getLabelName(jlPackingFullQuantityArrival.getText()) + "'.");
                            validation.setComponent(moDecPackingFullQuantityArrival);
                        }
                    }
                    else if (moDecPackingFullQuantityDeparture.isEditable() && moDecPackingFullQuantityDeparture.getValue() == 0) {
                        if (miClient.showMsgBoxConfirm("No tiene valor el campo '" + SGuiUtils.getLabelName(jlPackingFullQuantityDeparture.getText()) + "',\n" + SGuiConsts.MSG_CNF_CONT) != JOptionPane.YES_OPTION) {
                            validation.setMessage(SGuiConsts.ERR_MSG_FIELD_REQ + "'" + SGuiUtils.getLabelName(jlPackingFullQuantityDeparture.getText()) + "'.");
                            validation.setComponent(moDecPackingFullQuantityDeparture);
                        }
                    }
                    else {
                        // confirm a negative weight:
                        SDbTicket dummy = new SDbTicket();
                        dummy.setPackingFullQuantityArrival(moDecPackingFullQuantityArrival.getValue());
                        dummy.setPackingEmptyQuantityArrival(moDecPackingEmptyQuantityArrival.getValue());
                        dummy.setPackingFullQuantityDeparture(moDecPackingFullQuantityDeparture.getValue());
                        dummy.setPackingEmptyQuantityDeparture(moDecPackingEmptyQuantityDeparture.getValue());
                        dummy.setWeightDestinyArrival(moDecWeightDestinyArrival.getValue());
                        dummy.setWeightDestinyDeparture(moDecWeightDestinyDeparture.getValue());
                        dummy.setFkItemId(moKeyItem.getValue()[0]);
                        try {
                            dummy.computeWeight(miClient.getSession(), false);
                            if (dummy.getWeightDestinyNet_r() < 0) {
                                if (miClient.showMsgBoxConfirm("¡El peso neto del ticket es negativo (" + SLibUtils.getDecimalFormatQuantity().format(dummy.getWeightDestinyNet_r()) + ")!\n" + SGuiConsts.MSG_CNF_CONT) != JOptionPane.YES_OPTION) {
                                    validation.setMessage("¡Revisar los pesos de entrada y salida!");
                                }
                            }
                        }
                        catch (Exception e) {
                            SLibUtils.showException(this, e);
                        }
                    }
                }
                
                if (validation.isValid() && isFreightApply()) {
                    if (moRadFreight.isEnabled() && moRadDependent.isEnabled() && !(moRadFreight.isSelected() || moRadDependent.isSelected())) {
                        validation.setMessage("Se debe seleccionar una de las opciones:\n"
                                + "\t-" + moRadFreight.getText() + ".\n"
                                + "\t-" + moRadDependent.getText() + ".");
                        validation.setComponent(moRadFreight);
                    }
                    
                    if (validation.isValid() && moRadFreight.isEnabled() && moRadFreight.isSelected()) {
                        if (moKeyFreightOrigin.getValue()[0] == SModSysConsts.SU_FREIGHT_ORIG_NA) {
                            if (miClient.showMsgBoxConfirm(SGuiConsts.MSG_CNF_FIELD_VAL_  + "'" + SGuiUtils.getLabelName(jlFreightOrigin) + "' debe ser '" + moKeyFreightOrigin.getComponent().getSelectedItem().toString() + "'?") != JOptionPane.OK_OPTION) {
                                validation.setMessage(SGuiConsts.ERR_MSG_FIELD_DIF + "'" + SGuiUtils.getLabelName(jlFreightOrigin) + "'.");
                                validation.setComponent(moKeyFreightOrigin);
                            }
                        }
                    }
                }
            }
        }

        return validation;
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof JComboBox && e.getStateChange() == ItemEvent.SELECTED) {
            JComboBox comboBox = (JComboBox)  e.getSource();

            if (comboBox == moKeyItem) {
                itemStateKeyItem();
            }
            else if (comboBox == moKeyProducer) {
                itemStateKeyProducer();
            }
        }
        else if (e.getSource() instanceof JCheckBox) {
            JCheckBox checkBox = (JCheckBox)  e.getSource();

            if (checkBox == moBoolWeightSourceAvailable) {
                itemStateWeightSourceAvailable();
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();

            if (button == jbImportTicket) {
                actionImportTicket();
            }
            else if (button == jbCleanTicket) {
                actionCleanTicket();
            }
            else if (button == jbInputSource) {
                actionInputSource();
            }
            else if (button == jbImportTareTicket) {
                actionImportTareTicket();
            }
            else if (button == jbCleanTare) {
                actionCleanTare();
            }
            else if (button == jbSaveSend) {
                actionSaveSend();
            }
            else if (button == jbPackingFullQuantityArrival) {
                actionPackingFullQuantityArrival();
            }
            else if (button == jbPackingEmptyQuantityArrival) {
                actionPackingEmptyQuantityArrival();
            }
        }
        else if (e.getSource() instanceof JRadioButton) {
            JRadioButton button = (JRadioButton) e.getSource();
            
            if (button == moRadFreight) {
                actionRadEnableFreight();
            }
            else if (button == moRadDependent) {
                actionRadEnableFreight();
            }
        }
    }

    @Override
    public void focusGained(FocusEvent e) {

    }

    @Override
    public void focusLost(FocusEvent e) {
        if (e.getSource() instanceof javax.swing.JTextField) {
            JTextField textField = (JTextField) e.getSource();

            if (textField == moDecWeightSource.getComponent() ||
                textField == moDecWeightDestinyArrival.getComponent() ||
                textField == moDecWeightDestinyDeparture.getComponent() ||
                textField == moDecPackingFullQuantityArrival.getComponent() ||
                textField == moDecPackingEmptyQuantityArrival.getComponent() ||
                textField == moDecPackingFullQuantityDeparture.getComponent() ||
                textField == moDecPackingEmptyQuantityDeparture.getComponent()) {

                computeWeightAverage();
            }
        }
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        if (e.getSource() instanceof javax.swing.JSpinner) {
            JSpinner spinner = (JSpinner) e.getSource();
            
            if (spinner == moDatetimeArrival.getComponent()) {
                readRegion();
            }
        }
    }
}
