/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package som.mod.som.form;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToggleButton;
import javax.swing.border.TitledBorder;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.grid.SGridColumnForm;
import sa.lib.grid.SGridConsts;
import sa.lib.grid.SGridPaneForm;
import sa.lib.grid.SGridPaneFormOwner;
import sa.lib.grid.SGridRow;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanFieldRadio;
import sa.lib.gui.bean.SBeanFieldText;
import sa.lib.gui.bean.SBeanFormDialog;
import som.mod.SModConsts;
import som.mod.cfg.db.SDbField;
import som.mod.cfg.db.SDbValue;
import som.mod.som.db.SDbItem;

/**
 *
 * @author Sergio Flores
 */
public class SPickerValue extends SBeanFormDialog implements SGridPaneFormOwner, ActionListener, ItemListener, KeyListener {
    
    private SDbField moField;
    private SDbItem moTicketItem;
    private ArrayList<SDbValue> maAllValues;
    private ArrayList<SDbValue> maNewValues;
    private ArrayList<SDbValue> maElegibleValues;
    private SGridPaneForm moValuesGrid;
    private JLabel jlValuesShown;

    /**
     * Creates new form SPickerValue
     * @param client GUI client.
     * @param field Field type: SModSysContsts.C_FIELD_TIC_PLA or SModSysContsts.C_FIELD_TIC_DRV.
     * @param title Title.
     */
    public SPickerValue(SGuiClient client, int field, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.C_VALUE, field, msTitle);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgShow = new javax.swing.ButtonGroup();
        bgSearchType = new javax.swing.ButtonGroup();
        jpMain = new javax.swing.JPanel();
        jpSearch = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlTicketItem = new javax.swing.JLabel();
        jtfTicketItem = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jlTicketInputCategory = new javax.swing.JLabel();
        jtfTicketInputCategory = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jlValueText = new javax.swing.JLabel();
        jtfValueText = new javax.swing.JTextField();
        jbCopyValueText = new javax.swing.JButton();
        jlSearchType = new javax.swing.JLabel();
        moRadSearchExact = new sa.lib.gui.bean.SBeanFieldRadio();
        moRadSearchContent = new sa.lib.gui.bean.SBeanFieldRadio();
        jPanel5 = new javax.swing.JPanel();
        jlSearchText = new javax.swing.JLabel();
        moTextSearchText = new sa.lib.gui.bean.SBeanFieldText();
        jbClearSearchText = new javax.swing.JButton();
        jlShow = new javax.swing.JLabel();
        jtbShowElegible = new javax.swing.JToggleButton();
        jtbShowNew = new javax.swing.JToggleButton();
        jtbShowAll = new javax.swing.JToggleButton();
        jpValues = new javax.swing.JPanel();

        jpMain.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda de <field>:"));
        jpMain.setLayout(new java.awt.BorderLayout(0, 5));

        jpSearch.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTicketItem.setText("Ítem:");
        jlTicketItem.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlTicketItem);

        jtfTicketItem.setEditable(false);
        jtfTicketItem.setText("TEXT");
        jtfTicketItem.setFocusable(false);
        jtfTicketItem.setPreferredSize(new java.awt.Dimension(500, 23));
        jPanel3.add(jtfTicketItem);

        jpSearch.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlTicketInputCategory.setText("Categoría insumo:");
        jlTicketInputCategory.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlTicketInputCategory);

        jtfTicketInputCategory.setEditable(false);
        jtfTicketInputCategory.setText("TEXT");
        jtfTicketInputCategory.setFocusable(false);
        jtfTicketInputCategory.setPreferredSize(new java.awt.Dimension(500, 23));
        jPanel4.add(jtfTicketInputCategory);

        jpSearch.add(jPanel4);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlValueText.setText("<field>:");
        jlValueText.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel7.add(jlValueText);

        jtfValueText.setEditable(false);
        jtfValueText.setText("TEXT");
        jtfValueText.setFocusable(false);
        jtfValueText.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel7.add(jtfValueText);

        jbCopyValueText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_copy.gif"))); // NOI18N
        jbCopyValueText.setToolTipText("Copiar");
        jbCopyValueText.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel7.add(jbCopyValueText);

        jlSearchType.setText("   Búsqueda:");
        jlSearchType.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel7.add(jlSearchType);

        bgSearchType.add(moRadSearchExact);
        moRadSearchExact.setText("Exacta");
        moRadSearchExact.setPreferredSize(new java.awt.Dimension(85, 23));
        jPanel7.add(moRadSearchExact);

        bgSearchType.add(moRadSearchContent);
        moRadSearchContent.setText("Por contenido");
        moRadSearchContent.setPreferredSize(new java.awt.Dimension(175, 23));
        jPanel7.add(moRadSearchContent);

        jpSearch.add(jPanel7);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlSearchText.setText("Texto a buscar:");
        jlSearchText.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jlSearchText);

        moTextSearchText.setText("TEXT");
        moTextSearchText.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel5.add(moTextSearchText);

        jbClearSearchText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_delete.gif"))); // NOI18N
        jbClearSearchText.setToolTipText("Limpiar");
        jbClearSearchText.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel5.add(jbClearSearchText);

        jlShow.setText("   Mostrar:");
        jlShow.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel5.add(jlShow);

        bgShow.add(jtbShowElegible);
        jtbShowElegible.setText("Elegibles");
        jtbShowElegible.setToolTipText("Valores configurados para usarse con el ítem");
        jtbShowElegible.setPreferredSize(new java.awt.Dimension(85, 23));
        jPanel5.add(jtbShowElegible);

        bgShow.add(jtbShowNew);
        jtbShowNew.setText("Nuevos");
        jtbShowNew.setToolTipText("Valores que aún no están configurados para usarse con un ítem");
        jtbShowNew.setPreferredSize(new java.awt.Dimension(85, 23));
        jPanel5.add(jtbShowNew);

        bgShow.add(jtbShowAll);
        jtbShowAll.setText("Todos");
        jtbShowAll.setToolTipText("Todos los valores");
        jtbShowAll.setPreferredSize(new java.awt.Dimension(85, 23));
        jPanel5.add(jtbShowAll);

        jpSearch.add(jPanel5);

        jpMain.add(jpSearch, java.awt.BorderLayout.NORTH);

        jpValues.setLayout(new java.awt.BorderLayout());
        jpMain.add(jpValues, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSearchType;
    private javax.swing.ButtonGroup bgShow;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbClearSearchText;
    private javax.swing.JButton jbCopyValueText;
    private javax.swing.JLabel jlSearchText;
    private javax.swing.JLabel jlSearchType;
    private javax.swing.JLabel jlShow;
    private javax.swing.JLabel jlTicketInputCategory;
    private javax.swing.JLabel jlTicketItem;
    private javax.swing.JLabel jlValueText;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpSearch;
    private javax.swing.JPanel jpValues;
    private javax.swing.JToggleButton jtbShowAll;
    private javax.swing.JToggleButton jtbShowElegible;
    private javax.swing.JToggleButton jtbShowNew;
    private javax.swing.JTextField jtfTicketInputCategory;
    private javax.swing.JTextField jtfTicketItem;
    private javax.swing.JTextField jtfValueText;
    private sa.lib.gui.bean.SBeanFieldRadio moRadSearchContent;
    private sa.lib.gui.bean.SBeanFieldRadio moRadSearchExact;
    private sa.lib.gui.bean.SBeanFieldText moTextSearchText;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */
    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 800, 500);
        
        moTextSearchText.setTextSettings(SGuiUtils.getLabelName(jlSearchText), 100, 0);
        
        moFields.addField(moTextSearchText);
        moFields.setFormButton(jbSave);
        
        moField = (SDbField) miClient.getSession().readRegistry(SModConsts.C_FIELD, new int[] { mnFormSubtype });
        String fieldName = SLibUtils.textFirstUpperCase(moField.getName());
        
        ((TitledBorder) jpMain.getBorder()).setTitle(((TitledBorder) jpMain.getBorder()).getTitle().replace("<field>", moField.getName().toLowerCase()));
        jlValueText.setText(jlValueText.getText().replace("<field>", fieldName));
        
        moValuesGrid = new SGridPaneForm(miClient, mnFormType, mnFormSubtype, true, fieldName) {
            
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }
            
            @Override
            public void createGridColumns() {
                int col = 0;
                SGridColumnForm[] columns = new SGridColumnForm[4];

                columns[col++] = new SGridColumnForm(SGridConsts.COL_TYPE_TEXT_NAME_CAT_M, fieldName);
                columns[col++] = new SGridColumnForm(SGridConsts.COL_TYPE_TEXT_NAME_CAT_S, "Referencia");
                columns[col++] = new SGridColumnForm(SGridConsts.COL_TYPE_TEXT_NAME_CAT_M, "Aplica categorías insumo");
                columns[col++] = new SGridColumnForm(SGridConsts.COL_TYPE_TEXT_NAME_CAT_L, "Aplica ítems");

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };
        
        moValuesGrid.setPaneFormOwner(this);
        //mvFormGrids.add(moValuesGrid);

        jpValues.add(moValuesGrid, BorderLayout.CENTER);
        
        jlValuesShown = new JLabel();
        jlValuesShown.setPreferredSize(new Dimension(200, 23));
        jpCommandLeft.add(jlValuesShown);
        
        // default settings:
        
        moRadSearchExact.setSelected(true);
        jtbShowElegible.setSelected(true);
    }
    
    private void renderTicketItem() {
        if (moTicketItem == null) {
            jtfTicketItem.setText("");
            jtfTicketInputCategory.setText("");
        }
        else {
            jtfTicketItem.setText(moTicketItem.getName());
            jtfTicketInputCategory.setText((String) miClient.getSession().readField(SModConsts.SU_INP_CT, new int[] { moTicketItem.getFkInputCategoryId() }, SDbRegistry.FIELD_NAME));
            
            jtfTicketItem.setCaretPosition(0);
            jtfTicketInputCategory.setCaretPosition(0);
        }
    }
    
    private void showValues() {
        moValuesGrid.clearGridRows();
        jlValuesShown.setText("Valores mostrados: 0");
        
        ArrayList<SDbValue> availableValues = null;
        
        if (jtbShowAll.isSelected()) {
            availableValues = maAllValues;
        }
        else if (jtbShowNew.isSelected()) {
            availableValues = maNewValues;
        }
        else if (jtbShowElegible.isSelected()) {
            availableValues = maElegibleValues;
        }
        
        if (availableValues != null && !availableValues.isEmpty()) {
            ArrayList<SDbValue> values = new ArrayList<>();
            String text = moTextSearchText.getValue().toUpperCase();
            
            if (text.isEmpty()) {
                values.addAll(availableValues);
            }
            else {
                if (moRadSearchExact.isSelected()) {
                    for (SDbValue value : availableValues) {
                        if (value.getValueText().startsWith(text)) {
                            values.add(value);
                        }
                    }
                }
                else {
                    for (SDbValue value : availableValues) {
                        if (value.getValueText().contains(text)) {
                            values.add(value);
                        }
                    }
                }
            }
            
            moValuesGrid.populateGrid(new Vector<>(values));
            jlValuesShown.setText("Valores mostrados: " + SLibUtils.DecimalFormatInteger.format(values.size()));
        }
    }
    
    private void actionPerformedCopyValueText(final boolean requestFocus) {
        moTextSearchText.setValue(jtfValueText.getText());
        showValues();
        
        if (requestFocus) {
            moTextSearchText.requestFocusInWindow();
        }
    }
    
    private void actionPerformedClearSearchText() {
        moTextSearchText.resetField();
        showValues();
        
        moTextSearchText.requestFocusInWindow();
    }
    
    private void actionPerformedShow() {
        showValues();
    }
    
    /*
     * Overriden methods
     */
    
    @Override
    public void resetForm() {
        mnFormResult = 0;
        mbFirstActivation = true;
        
        moTicketItem = null;
        renderTicketItem();
        jtfValueText.setText("");
        moFields.resetFields();
    }
    
    @Override
    public void initForm() {
        removeAllListeners();
        
        reloadCatalogues();
        showValues();
        
        addAllListeners();
    }
    
    @Override
    public void addAllListeners() {
        jbCopyValueText.addActionListener(this);
        jbClearSearchText.addActionListener(this);
        jtbShowElegible.addActionListener(this);
        jtbShowNew.addActionListener(this);
        jtbShowAll.addActionListener(this);
        
        moRadSearchExact.addItemListener(this);
        moRadSearchContent.addItemListener(this);
        
        moTextSearchText.addKeyListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbCopyValueText.removeActionListener(this);
        jbClearSearchText.removeActionListener(this);
        jtbShowElegible.removeActionListener(this);
        jtbShowNew.removeActionListener(this);
        jtbShowAll.removeActionListener(this);
        
        moRadSearchExact.removeItemListener(this);
        moRadSearchContent.removeItemListener(this);
        
        moTextSearchText.removeKeyListener(this);
    }

    @Override
    public void reloadCatalogues() {
        try {
            maAllValues = moField.retriveValues(miClient.getSession());
            maNewValues = new ArrayList<>();
            maElegibleValues = new ArrayList<>();
            
            for (SDbValue value : maAllValues) {
                if (value.getScopeInputCategories().isEmpty() && value.getScopeItems().isEmpty()) {
                    maNewValues.add(value);
                }
            }
            
            for (SDbValue value : maAllValues) {
                if (value.getCompScopeInputCategoriesSet().contains(moTicketItem.getFkInputCategoryId()) || value.getCompScopeItemsSet().contains(moTicketItem.getPkItemId())) {
                    maElegibleValues.add(value);
                }
            }
        }
        catch (Exception e) {
            SLibUtils.showException(this, e);
        }
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();
        
        if (validation.isValid()) {
            if (moValuesGrid.getSelectedGridRow() == null) {
                validation.setMessage(SGridConsts.MSG_SELECT_ROW);
                validation.setComponent(moValuesGrid.getTable());
            }
        }
        
        return validation;
    }
    
    @Override
    public void setValue(final int type, final Object value) {
        switch (type) {
            case SModConsts.SU_ITEM:
                moTicketItem = (SDbItem) value;
                renderTicketItem();
                break;
            case SModConsts.C_VALUE:
                // value's text:
                jtfValueText.setText((String) value);
                jtfValueText.setCaretPosition(0);
                actionPerformedCopyValueText(false);
                break;
            default:
                // nothing
        }
    }
    
    @Override
    public Object getValue(final int type) {
        Object value = null;
        
        switch (type) {
            case SModConsts.C_VALUE:
                // value's text:
                SGridRow row = moValuesGrid.getSelectedGridRow();
                if (row != null) {
                    value = row.getRowName();
                }
                break;
            default:
                // nothing
        }
        
        return value;
    }

    @Override
    public void notifyRowNew(int gridType, int gridSubtype, int row, SGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void notifyRowEdit(int gridType, int gridSubtype, int row, SGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void notifyRowDelete(int gridType, int gridSubtype, int row, SGridRow gridRow) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();
            
            if (button == jbCopyValueText) {
                actionPerformedCopyValueText(true);
            }
            else if (button == jbClearSearchText) {
                actionPerformedClearSearchText();
            }
        }
        else if (e.getSource() instanceof JToggleButton) {
            JToggleButton toggleButton = (JToggleButton) e.getSource();
            
            if (toggleButton == jtbShowElegible || toggleButton == jtbShowNew || toggleButton == jtbShowAll) {
                actionPerformedShow();
            }
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        
    }

    @Override
    public void keyReleased(KeyEvent e) {
        if (e.getSource() instanceof SBeanFieldText) {
            if (e.getSource() == moTextSearchText) {
                showValues();
            }
        }
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof SBeanFieldRadio && e.getStateChange() == ItemEvent.SELECTED) {
            if (e.getSource() == moRadSearchExact || e.getSource() == moRadSearchContent) {
                showValues();
            }
        }
    }
}
