/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package som.mod.mat.form;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Calendar;
import sa.lib.SLibConsts;
import sa.lib.SLibTimeUtils;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanFieldKey;
import som.gui.SGuiClientUtils;
import som.mod.SModConsts;
import som.mod.SModSysConsts;
import som.mod.mat.db.SDbExwAdjustment;
import som.mod.som.db.SDbItem;

/**
 *
 * @author Sergio Flores
 */
public class SFormExwAdjustment extends sa.lib.gui.bean.SBeanForm implements ItemListener {

    private SDbExwAdjustment moRegistry;
    private SDbItem moItem;
    private int mnIogCategoryId;
    private String msIogCategory;
    private String msDefaultSeries;

    /**
     * Creates new form SFormExwAdjustment.
     * @param client GUI client.
     * @param formSubtype IOG category: SModSysConsts.SS_IOG_CT_IN or SModSysConsts.SS_IOG_CT_OUT.
     * @param title Form title.
     */
    public SFormExwAdjustment(SGuiClient client, int formSubtype, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.M_EXW_ADJ, formSubtype, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jlIogCategory = new javax.swing.JLabel();
        jtfIogCategory = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jlFolio = new javax.swing.JLabel();
        jtfFolio = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jlDate = new javax.swing.JLabel();
        moDate = new sa.lib.gui.bean.SBeanFieldDate();
        jtfOldDate = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jlExwAdjustmentType = new javax.swing.JLabel();
        moKeyExwAdjustmentType = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel6 = new javax.swing.JPanel();
        jlScale = new javax.swing.JLabel();
        moKeyScale = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel9 = new javax.swing.JPanel();
        jlExwFacility = new javax.swing.JLabel();
        moKeyExwFacility = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel10 = new javax.swing.JPanel();
        jlItem = new javax.swing.JLabel();
        moKeyItem = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel11 = new javax.swing.JPanel();
        jlQuantity = new javax.swing.JLabel();
        moCompQuantity = new sa.lib.gui.bean.SBeanCompoundField();
        jPanel4 = new javax.swing.JPanel();
        jlReference = new javax.swing.JLabel();
        moTextReference = new sa.lib.gui.bean.SBeanFieldText();
        jlCode2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlNote = new javax.swing.JLabel();
        moTextNote = new sa.lib.gui.bean.SBeanFieldText();
        jPanel14 = new javax.swing.JPanel();
        jchkAuthorized = new javax.swing.JCheckBox();
        jtfUserAuthorization = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(11, 1, 0, 5));

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlIogCategory.setText("Categoría mov.:");
        jlIogCategory.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel8.add(jlIogCategory);

        jtfIogCategory.setEditable(false);
        jtfIogCategory.setText("TEXT");
        jtfIogCategory.setFocusable(false);
        jtfIogCategory.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel8.add(jtfIogCategory);

        jPanel2.add(jPanel8);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlFolio.setText("Folio ajuste:");
        jlFolio.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel12.add(jlFolio);

        jtfFolio.setEditable(false);
        jtfFolio.setText("TEXT");
        jtfFolio.setFocusable(false);
        jtfFolio.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel12.add(jtfFolio);

        jPanel2.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDate.setText("Fecha ajuste:");
        jlDate.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel13.add(jlDate);
        jPanel13.add(moDate);

        jtfOldDate.setEditable(false);
        jtfOldDate.setText("TEXT");
        jtfOldDate.setToolTipText("Fecha original");
        jtfOldDate.setFocusable(false);
        jtfOldDate.setPreferredSize(new java.awt.Dimension(75, 23));
        jPanel13.add(jtfOldDate);

        jPanel2.add(jPanel13);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlExwAdjustmentType.setText("Tipo ajuste:*");
        jlExwAdjustmentType.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel7.add(jlExwAdjustmentType);

        moKeyExwAdjustmentType.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel7.add(moKeyExwAdjustmentType);

        jPanel2.add(jPanel7);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlScale.setText("Báscula:*");
        jlScale.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel6.add(jlScale);

        moKeyScale.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel6.add(moKeyScale);

        jPanel2.add(jPanel6);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlExwFacility.setText("Almacén externo:*");
        jlExwFacility.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel9.add(jlExwFacility);

        moKeyExwFacility.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel9.add(moKeyExwFacility);

        jPanel2.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlItem.setText("Ítem:*");
        jlItem.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel10.add(jlItem);

        moKeyItem.setPreferredSize(new java.awt.Dimension(500, 23));
        jPanel10.add(moKeyItem);

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlQuantity.setText("Cantidad:*");
        jlQuantity.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel11.add(jlQuantity);
        jPanel11.add(moCompQuantity);

        jPanel2.add(jPanel11);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlReference.setText("Referencia:");
        jlReference.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlReference);

        moTextReference.setText("TEXT");
        jPanel4.add(moTextReference);

        jlCode2.setForeground(java.awt.SystemColor.textInactiveText);
        jlCode2.setText("(Folio o número de referencia que soporta el movimiento)");
        jlCode2.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel4.add(jlCode2);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlNote.setText("Notas:*");
        jlNote.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jlNote);

        moTextNote.setText("TEXT");
        moTextNote.setPreferredSize(new java.awt.Dimension(500, 23));
        jPanel5.add(moTextNote);

        jPanel2.add(jPanel5);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jchkAuthorized.setText("Autorizado");
        jchkAuthorized.setEnabled(false);
        jchkAuthorized.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel14.add(jchkAuthorized);

        jtfUserAuthorization.setEditable(false);
        jtfUserAuthorization.setText("TEXT");
        jtfUserAuthorization.setFocusable(false);
        jtfUserAuthorization.setPreferredSize(new java.awt.Dimension(200, 23));
        jPanel14.add(jtfUserAuthorization);

        jPanel2.add(jPanel14);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JCheckBox jchkAuthorized;
    private javax.swing.JLabel jlCode2;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlExwAdjustmentType;
    private javax.swing.JLabel jlExwFacility;
    private javax.swing.JLabel jlFolio;
    private javax.swing.JLabel jlIogCategory;
    private javax.swing.JLabel jlItem;
    private javax.swing.JLabel jlNote;
    private javax.swing.JLabel jlQuantity;
    private javax.swing.JLabel jlReference;
    private javax.swing.JLabel jlScale;
    private javax.swing.JTextField jtfFolio;
    private javax.swing.JTextField jtfIogCategory;
    private javax.swing.JTextField jtfOldDate;
    private javax.swing.JTextField jtfUserAuthorization;
    private sa.lib.gui.bean.SBeanCompoundField moCompQuantity;
    private sa.lib.gui.bean.SBeanFieldDate moDate;
    private sa.lib.gui.bean.SBeanFieldKey moKeyExwAdjustmentType;
    private sa.lib.gui.bean.SBeanFieldKey moKeyExwFacility;
    private sa.lib.gui.bean.SBeanFieldKey moKeyItem;
    private sa.lib.gui.bean.SBeanFieldKey moKeyScale;
    private sa.lib.gui.bean.SBeanFieldText moTextNote;
    private sa.lib.gui.bean.SBeanFieldText moTextReference;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 640, 400);
        
        mnIogCategoryId = mnFormSubtype;
        
        switch (mnIogCategoryId) {
            case SModSysConsts.SS_IOG_CT_IN:
            case SModSysConsts.SS_IOG_CT_OUT:
                msIogCategory = miClient.getSession().readField(SModConsts.SS_IOG_CT, new int[] { mnIogCategoryId }, SDbRegistry.FIELD_NAME).toString();
                msDefaultSeries = isExwAdjustmentIn() ? SDbExwAdjustment.SERIES_IN : SDbExwAdjustment.SERIES_OUT;
                
                jtfIogCategory.setText(msIogCategory);
                jtfIogCategory.setCaretPosition(0);
                break;
                
            default:
                miClient.showMsgBoxWarning(SLibConsts.ERR_MSG_OPTION_UNKNOWN);
        }

        moDate.setDateSettings(miClient, SGuiUtils.getLabelName(jlDate), true);
        moKeyExwAdjustmentType.setKeySettings(miClient, SGuiUtils.getLabelName(jlExwAdjustmentType), true);
        moKeyScale.setKeySettings(miClient, SGuiUtils.getLabelName(jlScale), true);
        moKeyExwFacility.setKeySettings(miClient, SGuiUtils.getLabelName(jlExwFacility), true);
        moKeyItem.setKeySettings(miClient, SGuiUtils.getLabelName(jlItem), true);
        moCompQuantity.setCompoundFieldSettings(miClient);
        moCompQuantity.getField().setDecimalSettings(SGuiUtils.getLabelName(jlQuantity), SGuiConsts.GUI_TYPE_DEC_QTY, true);
        moTextReference.setTextSettings(SGuiUtils.getLabelName(jlReference.getText()), 10, 0);
        moTextNote.setTextSettings(SGuiUtils.getLabelName(jlNote.getText()), 255);

        moFields.addField(moDate);
        moFields.addField(moKeyExwAdjustmentType);
        moFields.addField(moKeyScale);
        moFields.addField(moKeyExwFacility);
        moFields.addField(moKeyItem);
        moFields.addField(moCompQuantity.getField());
        moFields.addField(moTextReference);
        moFields.addField(moTextNote);

        moFields.setFormButton(jbSave);
    }
    
    private boolean isExwAdjustmentIn() {
        return mnIogCategoryId == SModSysConsts.SS_IOG_CT_IN;
    }
    
    private void itemStateChangedItem() {
        if (moKeyItem.getSelectedIndex() <= 0) {
            moItem = null;
            moCompQuantity.setCompoundText("");
        }
        else {
            moItem = (SDbItem) miClient.getSession().readRegistry(SModConsts.SU_ITEM, moKeyItem.getValue());
            moCompQuantity.setCompoundText(miClient.getSession().readField(SModConsts.SU_UNIT, new int[] { moItem.getFkUnitId() }, SDbRegistry.FIELD_CODE).toString());
        }
    }

    @Override
    public void addAllListeners() {
        moKeyItem.addItemListener(this);
    }

    @Override
    public void removeAllListeners() {
        moKeyItem.removeItemListener(this);
    }

    @Override
    public void reloadCatalogues() {
        miClient.getSession().populateCatalogue(moKeyExwAdjustmentType, SModConsts.MU_EXW_ADJ_TP, mnIogCategoryId, null);
        miClient.getSession().populateCatalogue(moKeyScale, SModConsts.SU_SCA, 0, null);
        miClient.getSession().populateCatalogue(moKeyExwFacility, SModConsts.MU_EXW_FAC, 0, null);
        miClient.getSession().populateCatalogue(moKeyItem, SModConsts.SU_ITEM, 0, null);
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbExwAdjustment) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            moRegistry.initPrimaryKey();
            
            moRegistry.setSeries(msDefaultSeries);
            moRegistry.setDate(miClient.getSession().getWorkingDate());
            
            jtfOldDate.setText("");
            
            jtfRegistryKey.setText("");
        }
        else {
            jtfOldDate.setText(SLibUtils.DateFormatDate.format(moRegistry.getDate()));
            
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        jtfFolio.setText(moRegistry.getFolio());
        jtfFolio.setCaretPosition(0);
        
        moDate.setValue(moRegistry.getDate());
        moKeyExwAdjustmentType.setValue(new int[] { moRegistry.getFkExwAdjustmentTypeId() });
        moKeyScale.setValue(new int[] { moRegistry.getFkScaleId() });
        
        if (moRegistry.isRegistryNew()) {
            moKeyExwFacility.resetField(); // external warehouse facility "NA" has ID 0, so it cannot be selected by setValue()
        }
        else {
            moKeyExwFacility.setValue(new int[] { moRegistry.getFkExwFacilityId() });
        }
        
        moKeyItem.setValue(new int[] { moRegistry.getFkItemId() });
        itemStateChangedItem();
        
        moCompQuantity.getField().setValue(moRegistry.getQuantity());
        moTextReference.setValue(moRegistry.getReference());
        moTextNote.setValue(moRegistry.getNote());
        
        if (moRegistry.isAuthorized()) {
            jchkAuthorized.setSelected(true);
            jtfUserAuthorization.setText(miClient.getSession().readField(SModConsts.CU_USR, new int[] { moRegistry.getFkUserAuthorizationId() }, SDbRegistry.FIELD_NAME).toString());
            jtfUserAuthorization.setCaretPosition(0);
        }
        else {
            jchkAuthorized.setSelected(false);
            jtfUserAuthorization.setText("");
        }

        setFormEditable(true);

        if (moRegistry.isRegistryNew()) {
            
        }
        else {
            
        }

        addAllListeners();
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        SDbExwAdjustment registry = moRegistry.clone();

        if (registry.isRegistryNew()) {
            //registry.setPkExwAdjustmentId(...);
            //registry.setSeries(...);
            //registry.setNumber(...);
            registry.setFkIogCategoryId(mnIogCategoryId);
        }

        registry.setDate(moDate.getValue());
        registry.setReference(moTextReference.getValue());
        registry.setNote(moTextNote.getValue());
        registry.setQuantity(moCompQuantity.getField().getValue());
        //registry.setAuthorized(...);
        //registry.setDeleted(...);
        //registry.setSystem(...);
        registry.setFkExwAdjustmentTypeId(moKeyExwAdjustmentType.getValue()[0]);
        registry.setFkExwFacilityId(moKeyExwFacility.getValue()[0]);
        registry.setFkScaleId(moKeyScale.getValue()[0]);
        registry.setFkItemId(moItem.getPkItemId());
        registry.setFkUnitId(moItem.getFkUnitId());
        //registry.setFkUserInsertId(...);
        //registry.setFkUserUpdateId(...);
        //registry.setFkUserAuthorizationId(...);
        //registry.setTsUserInsert(...);
        //registry.setTsUserUpdate(...);
        //registry.setTsUserAuthorization(...);
        
        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();

        if (validation.isValid()) {
            int[] oldDate = !moRegistry.isRegistryNew() ? SLibTimeUtils.digestMonth(moRegistry.getOldDate()) : null;
            String[] months = SLibTimeUtils.createMonthsOfYearStd(Calendar.LONG);
            
            if (oldDate != null && !SLibTimeUtils.isBelongingToPeriod(moDate.getValue(), oldDate[0], oldDate[1])) {
                validation.setMessage("La nueva fecha, " + SLibUtils.DateFormatDate.format(moDate.getValue()) + ", debe pertenecer al mismo período de la fecha original, " + SLibUtils.DateFormatDate.format(moRegistry.getOldDate()) + ", " + months[oldDate[1] - 1] + " " + oldDate[0] + ".");
                validation.setComponent(moDate.getComponent());
            }
            else if (!SGuiClientUtils.isPeriodOpened(miClient.getSession(), moDate.getValue())) {
                int[] date = SLibTimeUtils.digestMonth(moDate.getValue());
                
                validation.setMessage("El período actual, " + months[date[1] - 1] + " " + date[0] + ", está cerrado.");
                validation.setComponent(moDate.getComponent());
            }
        }
        
        return validation;
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof SBeanFieldKey && e.getStateChange() == ItemEvent.SELECTED) {
            SBeanFieldKey field = (SBeanFieldKey) e.getSource();
            
            if (field == moKeyItem) {
                itemStateChangedItem();
            }
        }
    }
}
