/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package som.mod.cfg.form;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JButton;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.grid.SGridColumnForm;
import sa.lib.grid.SGridConsts;
import sa.lib.grid.SGridPaneForm;
import sa.lib.grid.SGridRow;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanForm;
import som.mod.SModConsts;
import som.mod.SModSysConsts;
import som.mod.cfg.db.SDbUser;
import som.mod.cfg.db.SDbUserRightAlternative;

/**
 *
 * @author Sergio Flores, Isabel Servín 
 */
public class SFormUserAlternative extends SBeanForm implements ActionListener {

    private SDbUser moRegistry;
    private SGridPaneForm moGridUserRights;
    
    /**
     * Creates new form SFormUser
     * @param client
     * @param title
     */
    public SFormUserAlternative(SGuiClient client, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.CU_USR_ALT_RIG, SLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        moTextName = new sa.lib.gui.bean.SBeanFieldText();
        jPanel6 = new javax.swing.JPanel();
        jpUserRights = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(1, 1, 0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlName.setText("Nombre:*");
        jlName.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlName);

        moTextName.setEditable(false);
        moTextName.setText("sBeanFieldText1");
        moTextName.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel3.add(moTextName);

        jPanel2.add(jPanel3);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel6.setLayout(new java.awt.GridLayout(1, 1));

        jpUserRights.setBorder(javax.swing.BorderFactory.createTitledBorder("Derechos de usuario:"));
        jpUserRights.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jpUserRights);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jlName;
    private javax.swing.JPanel jpUserRights;
    private sa.lib.gui.bean.SBeanFieldText moTextName;
    // End of variables declaration//GEN-END:variables

    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 880, 550);

        moTextName.setTextSettings(SGuiUtils.getLabelName(jlName.getText()), 16);
        moTextName.setTextCaseType(SGuiConsts.TEXT_CASE_LOWER);
        
        moFields.addField(moTextName);
        
        moFields.setFormButton(jbSave);

        
        moGridUserRights = new SGridPaneForm(miClient, SModConsts.CS_ALT_RIG, 1, "Usuarios vs. derechos alternativos") {
            @Override
            public void initGrid() {
                setRowButtonsEnabled(false);
            }

            @Override
            public void createGridColumns() {
                int col = 0;
                SGridColumnForm[] columns = new SGridColumnForm[2];

                columns[col++] = new SGridColumnForm(SGridConsts.COL_TYPE_TEXT_NAME_CAT_M, "Derecho");
                columns[col] = new SGridColumnForm(SGridConsts.COL_TYPE_BOOL_S, "Seleccionado");
                columns[col++].setEditable(true);

                for (col = 0; col < columns.length; col++) {
                    moModel.getGridColumns().add(columns[col]);
                }
            }
        };

        moGridUserRights.setForm(null);
        moGridUserRights.setPaneFormOwner(null);
        jpUserRights.add(moGridUserRights, BorderLayout.CENTER);

        
    }

    private void populateUserRights() throws SQLException {
        Vector<SGridRow> rows = new Vector<>();
        String sql = "SELECT id_alt_rig, name FROM " + SModConsts.TablesMap.get(SModConsts.CS_ALT_RIG) + " WHERE b_del = 0 ORDER BY sort ";
        
        try (ResultSet resultSet = miClient.getSession().getStatement().executeQuery(sql)) {
            while (resultSet.next()) {
                SDbUserRightAlternative row = new SDbUserRightAlternative();
                row.setPkRightId(resultSet.getInt(1));
                row.setXtaRight(resultSet.getString(2));
                rows.add(row);
            }
        }

        moGridUserRights.populateGrid(rows);
    }

    
    @Override
    public void addAllListeners() {

    }

    @Override
    public void removeAllListeners() {

    }

    @Override
    public void reloadCatalogues() {
        
        try {
            populateUserRights();
            
        }
        catch (SQLException e) {
            SLibUtils.showException(this, e);
        }
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbUser) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            moRegistry.initPrimaryKey();
            jtfRegistryKey.setText("");
            moRegistry.setFkUserTypeId(SModSysConsts.CS_USR_TP_USR);
        }
        else {
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moTextName.setValue(moRegistry.getName());
        

        for (SDbUserRightAlternative right : moRegistry.getChildUserRightsAlternatives()) {
            for (SGridRow row : moGridUserRights.getModel().getGridRows()) {
                if (right.getPkRightId() == ((SDbUserRightAlternative) row).getPkRightId()) {
                    ((SDbUserRightAlternative) row).setXtaSelected(true);
                }
            }
        }

        
        setFormEditable(true);

        if (moRegistry.isRegistryNew()) {
        
        }
                
        addAllListeners();
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        SDbUser registry = moRegistry.clone();

        if (registry.isRegistryNew()) {}

        //registry.setName(moTextName.getValue());
       
        registry.getChildUserRightsAlternatives().clear();
        for (SGridRow row : moGridUserRights.getModel().getGridRows()) {
            if (((SDbUserRightAlternative) row).isXtaSelected()) {
                registry.getChildUserRightsAlternatives().add((SDbUserRightAlternative) row);
            }
        }

        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();

        return validation;
    }

    @Override
    public void actionPerformed(ActionEvent evt) {
        if (evt.getSource() instanceof JButton) {
            JButton button = (JButton) evt.getSource();
            
        }
    }
}
