/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package som.mod.cfg.form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanFieldKey;
import sa.lib.gui.bean.SBeanFieldText;
import som.mod.SModConsts;
import som.mod.cfg.db.SDbField;
import som.mod.cfg.db.SDbValue;

/**
 *
 * @author Sergio Flores
 */
public class SFormValue extends sa.lib.gui.bean.SBeanForm implements ActionListener, ItemListener{

    private SDbValue moRegistry;
    private SDbField moField;

    /**
     * Creates new form SFormValue
     * @param client GUI client.
     * @param field Field type: SModSysContsts.C_FIELD_TIC_PLA or SModSysContsts.C_FIELD_TIC_DRV.
     * @param title Title.
     */
    public SFormValue(SGuiClient client, int field, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.C_VALUE, field, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jlField = new javax.swing.JLabel();
        moKeyField = new sa.lib.gui.bean.SBeanFieldKey();
        jPanel9 = new javax.swing.JPanel();
        jlFieldDescription = new javax.swing.JLabel();
        jtfFieldDescription = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jlFieldSettings = new javax.swing.JLabel();
        jtfFieldSettings = new javax.swing.JTextField();
        jbViewFieldSettings = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jlFieldTrimCharacters = new javax.swing.JLabel();
        jtfFieldTrimCharacters = new javax.swing.JTextField();
        jlFieldTrimCharactersHint = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jlValueText = new javax.swing.JLabel();
        moTextValueText = new sa.lib.gui.bean.SBeanFieldText();
        jbEditValueText = new javax.swing.JButton();
        jlValueText1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlValueReference = new javax.swing.JLabel();
        moTextValueReference = new sa.lib.gui.bean.SBeanFieldText();
        jPanel6 = new javax.swing.JPanel();
        jlScopeInputCategories = new javax.swing.JLabel();
        moTextScopeInputCategories = new sa.lib.gui.bean.SBeanFieldText();
        jbEditScopeInputCategories = new javax.swing.JButton();
        jlScopeInputCategoriesHint = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jlScopeItems = new javax.swing.JLabel();
        moTextScopeItems = new sa.lib.gui.bean.SBeanFieldText();
        jbEditScopeItems = new javax.swing.JButton();
        jlScopeItemsHint = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(9, 1, 0, 5));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlField.setForeground(new java.awt.Color(0, 0, 255));
        jlField.setText("Campo:*");
        jlField.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel7.add(jlField);

        moKeyField.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel7.add(moKeyField);

        jPanel2.add(jPanel7);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlFieldDescription.setText("Descripción:");
        jlFieldDescription.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel9.add(jlFieldDescription);

        jtfFieldDescription.setEditable(false);
        jtfFieldDescription.setText("jTextField1");
        jtfFieldDescription.setFocusable(false);
        jtfFieldDescription.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel9.add(jtfFieldDescription);

        jPanel2.add(jPanel9);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlFieldSettings.setText("Configuración:");
        jlFieldSettings.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel10.add(jlFieldSettings);

        jtfFieldSettings.setEditable(false);
        jtfFieldSettings.setText("jTextField1");
        jtfFieldSettings.setFocusable(false);
        jtfFieldSettings.setPreferredSize(new java.awt.Dimension(400, 23));
        jPanel10.add(jtfFieldSettings);

        jbViewFieldSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_look.gif"))); // NOI18N
        jbViewFieldSettings.setToolTipText("Ver configuración...");
        jbViewFieldSettings.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel10.add(jbViewFieldSettings);

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlFieldTrimCharacters.setText("Remoción:");
        jlFieldTrimCharacters.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel11.add(jlFieldTrimCharacters);

        jtfFieldTrimCharacters.setEditable(false);
        jtfFieldTrimCharacters.setText("jTextField1");
        jtfFieldTrimCharacters.setFocusable(false);
        jtfFieldTrimCharacters.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel11.add(jtfFieldTrimCharacters);

        jlFieldTrimCharactersHint.setForeground(java.awt.SystemColor.textInactiveText);
        jlFieldTrimCharactersHint.setText("(carácteres no permitidos, deberán ser removidos)");
        jlFieldTrimCharactersHint.setPreferredSize(new java.awt.Dimension(273, 23));
        jPanel11.add(jlFieldTrimCharactersHint);

        jPanel2.add(jPanel11);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlValueText.setText("Valor:*");
        jlValueText.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jlValueText);

        moTextValueText.setText("sBeanFieldText1");
        moTextValueText.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel5.add(moTextValueText);

        jbEditValueText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_edit.gif"))); // NOI18N
        jbEditValueText.setToolTipText("Modificar");
        jbEditValueText.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel5.add(jbEditValueText);

        jlValueText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_view_info.png"))); // NOI18N
        jlValueText1.setToolTipText("El valor no puede repetirse en el catálogo, y debe cumplir con la configuración del campo");
        jlValueText1.setPreferredSize(new java.awt.Dimension(18, 23));
        jPanel5.add(jlValueText1);

        jPanel2.add(jPanel5);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlValueReference.setText("Referencia:");
        jlValueReference.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlValueReference);

        moTextValueReference.setText("sBeanFieldText1");
        moTextValueReference.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel4.add(moTextValueReference);

        jPanel2.add(jPanel4);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlScopeInputCategories.setText("Categorías insumo:");
        jlScopeInputCategories.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel6.add(jlScopeInputCategories);

        moTextScopeInputCategories.setText("sBeanFieldText1");
        moTextScopeInputCategories.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel6.add(moTextScopeInputCategories);

        jbEditScopeInputCategories.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_edit.gif"))); // NOI18N
        jbEditScopeInputCategories.setToolTipText("Modificar");
        jbEditScopeInputCategories.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel6.add(jbEditScopeInputCategories);

        jlScopeInputCategoriesHint.setForeground(java.awt.SystemColor.textInactiveText);
        jlScopeInputCategoriesHint.setText("(ID separados por coma, sin espacios)");
        jlScopeInputCategoriesHint.setPreferredSize(new java.awt.Dimension(225, 23));
        jPanel6.add(jlScopeInputCategoriesHint);

        jPanel2.add(jPanel6);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlScopeItems.setText("Ítems:");
        jlScopeItems.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel8.add(jlScopeItems);

        moTextScopeItems.setText("sBeanFieldText1");
        moTextScopeItems.setPreferredSize(new java.awt.Dimension(150, 23));
        jPanel8.add(moTextScopeItems);

        jbEditScopeItems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/som/gui/img/icon_std_edit.gif"))); // NOI18N
        jbEditScopeItems.setToolTipText("Modificar");
        jbEditScopeItems.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel8.add(jbEditScopeItems);

        jlScopeItemsHint.setForeground(java.awt.SystemColor.textInactiveText);
        jlScopeItemsHint.setText("(ID separados por coma, sin espacios)");
        jlScopeItemsHint.setPreferredSize(new java.awt.Dimension(225, 23));
        jPanel8.add(jlScopeItemsHint);

        jPanel2.add(jPanel8);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbEditScopeInputCategories;
    private javax.swing.JButton jbEditScopeItems;
    private javax.swing.JButton jbEditValueText;
    private javax.swing.JButton jbViewFieldSettings;
    private javax.swing.JLabel jlField;
    private javax.swing.JLabel jlFieldDescription;
    private javax.swing.JLabel jlFieldSettings;
    private javax.swing.JLabel jlFieldTrimCharacters;
    private javax.swing.JLabel jlFieldTrimCharactersHint;
    private javax.swing.JLabel jlScopeInputCategories;
    private javax.swing.JLabel jlScopeInputCategoriesHint;
    private javax.swing.JLabel jlScopeItems;
    private javax.swing.JLabel jlScopeItemsHint;
    private javax.swing.JLabel jlValueReference;
    private javax.swing.JLabel jlValueText;
    private javax.swing.JLabel jlValueText1;
    private javax.swing.JTextField jtfFieldDescription;
    private javax.swing.JTextField jtfFieldSettings;
    private javax.swing.JTextField jtfFieldTrimCharacters;
    private sa.lib.gui.bean.SBeanFieldKey moKeyField;
    private sa.lib.gui.bean.SBeanFieldText moTextScopeInputCategories;
    private sa.lib.gui.bean.SBeanFieldText moTextScopeItems;
    private sa.lib.gui.bean.SBeanFieldText moTextValueReference;
    private sa.lib.gui.bean.SBeanFieldText moTextValueText;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */
    
    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 560, 350);

        moKeyField.setKeySettings(miClient, SGuiUtils.getLabelName(jlField), true);
        moTextValueText.setTextSettings(SGuiUtils.getLabelName(jlValueText), 100);
        moTextValueReference.setTextSettings(SGuiUtils.getLabelName(jlValueReference.getText()), 100, 0);
        moTextScopeInputCategories.setTextSettings(SGuiUtils.getLabelName(jlScopeInputCategories), 25, 0);
        moTextScopeItems.setTextSettings(SGuiUtils.getLabelName(jlScopeItems), 25, 0);

        moFields.addField(moKeyField);
        moFields.addField(moTextValueText);
        moFields.addField(moTextValueReference);
        moFields.addField(moTextScopeInputCategories);
        moFields.addField(moTextScopeItems);

        moFields.setFormButton(jbSave);
    }
    
    private void renderField() {
        if (moField == null) {
            jtfFieldDescription.setText("");
            jtfFieldSettings.setText("");
            jtfFieldTrimCharacters.setText("");
            
            jtfFieldDescription.setToolTipText(null);
            jtfFieldSettings.setToolTipText(null);
            jtfFieldTrimCharacters.setToolTipText(null);
            
            jbViewFieldSettings.setEnabled(false);
        }
        else {
            jtfFieldDescription.setText(moField.getDescription());
            jtfFieldSettings.setText(moField.getSettings());
            jtfFieldTrimCharacters.setText(moField.getTrimCharacters());
            
            jtfFieldDescription.setCaretPosition(0);
            jtfFieldSettings.setCaretPosition(0);
            jtfFieldTrimCharacters.setCaretPosition(0);
            
            jtfFieldDescription.setToolTipText(jtfFieldDescription.getText());
            jtfFieldSettings.setToolTipText(jtfFieldSettings.getText());
            jtfFieldTrimCharacters.setToolTipText(jtfFieldTrimCharacters.getText());
            
            jbViewFieldSettings.setEnabled(true);
        }
    }

    private void actionPerformedViewFieldSettings() {
        miClient.showMsgBoxInformation("" + moField);
    }
    
    private void actionPerformedEditValueText() {
        jbEditValueText.setEnabled(false);
        moTextValueText.setEditable(true);
        moTextValueText.requestFocusInWindow();
    }
    
    private void actionPerformedEditScopeInputCategories() {
        jbEditScopeInputCategories.setEnabled(false);
        moTextScopeInputCategories.setEditable(true);
        moTextScopeInputCategories.requestFocusInWindow();
    }
    
    private void actionPerformedEditScopeItems() {
        jbEditScopeItems.setEnabled(false);
        moTextScopeItems.setEditable(true);
        moTextScopeItems.requestFocusInWindow();
    }
    
    private void itemStateChangedField() {
        if (moKeyField.getSelectedIndex() <= 0) {
            moField = null;
        }
        else {
            moField = (SDbField) miClient.getSession().readRegistry(SModConsts.C_FIELD, moKeyField.getValue());
        }
        
        renderField();
    }
    
    /*
     * Overriden methods
     */

    @Override
    public void addAllListeners() {
        jbViewFieldSettings.addActionListener(this);
        jbEditValueText.addActionListener(this);
        jbEditScopeInputCategories.addActionListener(this);
        jbEditScopeItems.addActionListener(this);
        
        moKeyField.addItemListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbViewFieldSettings.removeActionListener(this);
        jbEditValueText.removeActionListener(this);
        jbEditScopeInputCategories.removeActionListener(this);
        jbEditScopeItems.removeActionListener(this);
        
        moKeyField.removeItemListener(this);
    }

    @Override
    public void reloadCatalogues() {
        miClient.getSession().populateCatalogue(moKeyField, SModConsts.C_FIELD, 0, null);
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbValue) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            moRegistry.initPrimaryKey();
            
            moKeyField.setValue(new int[] { mnFormSubtype });
            
            jtfRegistryKey.setText("");
        }
        else {
            moKeyField.setValue(new int[] { moRegistry.getFkFieldId() });
            
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }
        
        itemStateChangedField();

        moTextValueText.setValue(moRegistry.getValueText());
        moTextValueReference.setValue(moRegistry.getValueReference());
        moTextScopeInputCategories.setValue(moRegistry.getScopeInputCategories());
        moTextScopeItems.setValue(moRegistry.getScopeItems());

        setFormEditable(true);
        
        moKeyField.setEnabled(false); // immutable value
        
        if (moRegistry.isRegistryNew()) {
            jbEditValueText.setEnabled(false);
            jbEditScopeInputCategories.setEnabled(false);
            jbEditScopeItems.setEnabled(false);
        }
        else {
            jbEditValueText.setEnabled(true);
            jbEditScopeInputCategories.setEnabled(true);
            jbEditScopeItems.setEnabled(true);
            
            moTextValueText.setEditable(false);
            moTextScopeInputCategories.setEditable(false);
            moTextScopeItems.setEditable(false);
        }

        addAllListeners();
    }

    @Override
    public SDbRegistry getRegistry() throws Exception {
        SDbValue registry = moRegistry.clone();
        
        if (registry.isRegistryNew()) {
            registry.setFkFieldId(moKeyField.getValue()[0]); // immutable value
        }

        registry.setValueText(moTextValueText.getValue());
        registry.setValueReference(moTextValueReference.getValue());
        registry.setScopeInputCategories(moTextScopeInputCategories.getValue());
        registry.setScopeItems(moTextScopeItems.getValue());

        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        // sanitize data:
        
        SGuiValidation validation = new SGuiValidation();
        
        HashMap<Integer, SBeanFieldText> fields = new HashMap<>(); // key: fieldId; value: text field
        HashMap<Integer, String> sanitizedValues = new HashMap<>(); // key: fieldId; value: sanitized value
        
        if (moTextValueText.isEditable()) {
            fields.put(1, moTextValueText);
            sanitizedValues.put(1, moField.sanitizeValueText(moTextValueText.getValue()));
        }
        if (moTextScopeInputCategories.isEditable() && !moTextScopeInputCategories.getValue().isEmpty()) {
            fields.put(2, moTextScopeInputCategories);
            sanitizedValues.put(2, SDbValue.sanitizeDataIds(moTextScopeInputCategories.getValue()));
        }
        if (moTextScopeItems.isEditable() && !moTextScopeItems.getValue().isEmpty()) {
            fields.put(3, moTextScopeItems);
            sanitizedValues.put(3, SDbValue.sanitizeDataIds(moTextScopeItems.getValue()));
        }
        
        for (Integer fieldId : sanitizedValues.keySet()) {
            SBeanFieldText field = fields.get(fieldId);
            String sanitizedValue = sanitizedValues.get(fieldId);
            
            if (!field.getValue().equals(sanitizedValue)) {
                String action = (sanitizedValue.isEmpty() ? "será borrado totalmente" : "será sustituido por el valor '" + sanitizedValue + "'") + ".";
                
                if (miClient.showMsgBoxConfirm(SGuiConsts.ERR_MSG_FIELD_VAL_ + "'" + field.getFieldName() + "', '" + field.getValue() + "',\n"
                        + "no cumple con el formato requerido, por lo " + action + "\n" + SGuiConsts.MSG_CNF_CONT) == JOptionPane.YES_OPTION) {
                    field.setValue(sanitizedValue);
                }
                else {
                    validation.setMessage(SGuiConsts.ERR_MSG_FIELD_DIF + "'" + field.getFieldName() + "'.");
                    validation.setComponent(field);
                }
            }
        }
        
        // validate data:
        
        if (validation.isValid()) {
            validation = moFields.validateFields();
            JComponent component = null;

            // check text value for no duplicity and formatting rules:

            try {
                if (validation.isValid()) {
                    if (moTextValueText.isEditable()) {
                        component = moTextValueText;

                        // an exception will be thrown on validation failure:
                        moField.validateValueTextFormat(miClient, moTextValueText.getValue());

                        int count = SDbValue.countOccurrences(miClient.getSession(), moKeyField.getValue()[0], moTextValueText.getValue(), moRegistry.getPkValueId());

                        if (count > 0) {
                            validation.setMessage("¡El valor '" + moTextValueText.getValue() + "', para el campo '" + moField.getName() + "', ya existe en el catálogo!");
                            validation.setComponent(moTextValueText);
                        }
                        else {
                            String similarValues = "";
                            ArrayList<SDbValue> values = SDbValue.retrieveSimilars(miClient.getSession(), moKeyField.getValue()[0], moTextValueText.getValue(), moRegistry.getPkValueId());
                            
                            if (!values.isEmpty()) {
                                int i = 0;
                                for (SDbValue value : values) {
                                    similarValues += "\n" + ++i + ". " + value.getValueText() + (value.isDeleted() ? " (eliminado)" : "");
                                }
                                
                                String confirm = "Se " + (values.size() == 1 ? "encontró 1 valor similar" : "encontraron " + values.size() + " valores similares")
                                        + " a '" + moTextValueText.getValue() + "', para el campo '" + moField.getName() + "':";
                                
                                if (miClient.showMsgBoxConfirm(confirm + similarValues + "\n"
                                        + "¡Revise cuidadosamente para evitar crear valores duplicados!\n"
                                        + "¿Está seguro de que el valor '" + moTextValueText.getValue() + "' es realmente diferente?") != JOptionPane.YES_OPTION) {
                                    validation.setMessage("Favor de asegurarse de que el valor '" + moTextValueText.getValue() + "' sea en realidad diferente a:" + similarValues + "\n"
                                            + "En caso contrario, evite crear valores duplicados para el campo '" + moField.getName() + "'\n"
                                            + "Corrija el valor '" + moTextValueText.getValue() + "' o dé clic en '" + jbCancel.getText() + "' para abortar la captura.");
                                    validation.setComponent(moTextValueText);
                                }
                            }
                        }
                    }

                    if (validation.isValid()) {
                        if (moTextScopeInputCategories.isEditable() && !moTextScopeInputCategories.getValue().isEmpty()) {
                            component = moTextScopeInputCategories;

                            // an exception will be thrown on validation failure:
                            SDbValue.validateDataIds(miClient.getSession(), SModConsts.SU_INP_CT, moTextScopeInputCategories.getValue());
                        }

                        if (moTextScopeItems.isEditable() && !moTextScopeItems.getValue().isEmpty()) {
                            component = moTextScopeItems;

                            // an exception will be thrown on validation failure:
                            SDbValue.validateDataIds(miClient.getSession(), SModConsts.SU_ITEM, moTextScopeItems.getValue());
                        }
                    }
                }
            }
            catch (Exception e) {
                validation.setMessage(e.getMessage());
                validation.setComponent(component);
            }
        }

        return validation;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();
            
            if (button == jbViewFieldSettings) {
                actionPerformedViewFieldSettings();
            }
            else if (button == jbEditValueText) {
                actionPerformedEditValueText();
            }
            else if (button == jbEditScopeInputCategories) {
                actionPerformedEditScopeInputCategories();
            }
            else if (button == jbEditScopeItems) {
                actionPerformedEditScopeItems();
            }
        }
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        if (e.getSource() instanceof SBeanFieldKey && e.getStateChange() == ItemEvent.SELECTED) {
            SBeanFieldKey field = (SBeanFieldKey) e.getSource();
            
            if (field == moKeyField) {
                itemStateChangedField();
            }
        }
    }
}
